# Generated by Django 2.1.15 on 2024-07-02 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0002_auto_20240628_1503'),
        ('clinico', '0002_auto_20240628_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicos',
            old_name='id_centro',
            new_name='centro',
        ),
        migrations.RenameField(
            model_name='medicos',
            old_name='id_ciudad',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='medicos',
            old_name='id_departamento',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='medicos',
            old_name='id_especialidad',
            new_name='especialidad',
        ),
        migrations.RenameField(
            model_name='medicos',
            old_name='id_tipo_doc',
            new_name='tipoDoc',
        ),
        migrations.AddField(
            model_name='medicos',
            name='perfilesPlanta',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.PerfilesPlanta'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='planta',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
    ]
