# Generated by Django 2.1.15 on 2024-07-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0003_auto_20240702_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicos',
            old_name='especialidad',
            new_name='especialidades',
        ),
    ]
