# Generated by Django 2.1.15 on 2024-07-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0004_auto_20240702_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicos',
            name='perfilesPlanta',
        ),
        migrations.AddField(
            model_name='medicos',
            name='registroMedico',
            field=models.CharField(default='', max_length=50),
        ),
    ]
