# Generated by Django 2.1.15 on 2024-07-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0008_hallazgos'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticos',
            name='edadFin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticos',
            name='edadIni',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticos',
            name='flagSivigila',
            field=models.CharField(choices=[('S', 'S'), ('N', 'N')], default='A', editable=False, max_length=1),
        ),
    ]
