# Generated by Django 2.1.15 on 2024-07-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0010_nivelesregimenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelesregimenes',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
