# Generated by Django 2.1.15 on 2024-07-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0015_formasfarmaceuticas_presentacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrecuenciasAplicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoMipres', models.DecimalField(decimal_places=0, max_digits=5)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('habilitadoMipres', models.CharField(blank=True, max_length=1, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadesDeMedidaDosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoMipres', models.DecimalField(decimal_places=0, max_digits=5)),
                ('unidadaDeMedidaPrincipioA', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('habilitadoMipres', models.CharField(blank=True, max_length=1, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
    ]
