# Generated by Django 2.1.15 on 2024-07-18 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0017_indicacionesespeciales_tiposmedicamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpedienteDCI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoMipres', models.DecimalField(decimal_places=0, max_digits=5)),
                ('habilitadoMipres', models.CharField(blank=True, max_length=1, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('formaFarmaceutica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.FormasFarmaceuticas')),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentosDci',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoMipres', models.DecimalField(decimal_places=0, max_digits=5)),
                ('descripcionDciConcentracion', models.CharField(blank=True, max_length=100, null=True)),
                ('habilitadoMipres', models.CharField(blank=True, max_length=1, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('tipoMedicamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposMedicamento')),
            ],
        ),
    ]
