# Generated by Django 2.1.15 on 2024-07-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0019_tiposdispositivomedico_tiposproductosnutricion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosNutricion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoMipres', models.DecimalField(decimal_places=0, max_digits=5)),
                ('nombreComercial', models.CharField(blank=True, max_length=100, null=True)),
                ('grupo', models.CharField(blank=True, max_length=100, null=True)),
                ('habilitadoMipres', models.CharField(blank=True, max_length=1, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('formaFarmaceutica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.FormasFarmaceuticas')),
                ('presentacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Presentacion')),
                ('unidades', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.UnidadesDeMedida')),
            ],
        ),
    ]
