# Generated by Django 2.1.15 on 2024-07-18 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0020_productosnutricion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoria7', to='usuarios.Usuarios'),
        ),
    ]
