# Generated by Django 2.1.15 on 2024-07-18 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20240710_1531'),
        ('planta', '0003_auto_20240702_1521'),
        ('clinico', '0021_auto_20240718_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consecAdmision', models.IntegerField(default=0)),
                ('folio', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField()),
                ('frecCardiaca', models.DecimalField(decimal_places=2, max_digits=3)),
                ('frecRespiratoria', models.DecimalField(decimal_places=2, max_digits=3)),
                ('tensionADiastolica', models.DecimalField(decimal_places=2, max_digits=3)),
                ('tensionASistolica', models.DecimalField(decimal_places=2, max_digits=3)),
                ('tensionAMedia', models.DecimalField(decimal_places=2, max_digits=3)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('saturacion', models.DecimalField(decimal_places=2, max_digits=3)),
                ('glucometria', models.DecimalField(decimal_places=2, max_digits=3)),
                ('glasgow', models.DecimalField(decimal_places=2, max_digits=3)),
                ('apache', models.DecimalField(decimal_places=2, max_digits=3)),
                ('pvc', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cuna', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ic', models.DecimalField(decimal_places=2, max_digits=3)),
                ('glasgowOcular', models.DecimalField(decimal_places=2, max_digits=3)),
                ('glagowVerbal', models.DecimalField(decimal_places=2, max_digits=3)),
                ('glasgowMotora', models.DecimalField(decimal_places=2, max_digits=3)),
                ('observacion', models.CharField(blank=True, max_length=5000)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoria78', to='usuarios.Usuarios')),
                ('tipoDoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta')),
            ],
        ),
    ]
