# Generated by Django 2.1.15 on 2024-07-18 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20240710_1531'),
        ('planta', '0003_auto_20240702_1521'),
        ('clinico', '0024_trasfusiones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oxigeno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consecAdmision', models.IntegerField(default=0)),
                ('folio', models.IntegerField(default=0)),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFinal', models.DateTimeField()),
                ('tipoOxigenacion', models.CharField(blank=True, max_length=15)),
                ('aire', models.CharField(blank=True, max_length=1)),
                ('saturacionOxigeno', models.DecimalField(decimal_places=2, max_digits=3)),
                ('flujoLtsOxigeno', models.DecimalField(decimal_places=2, max_digits=3)),
                ('flujoLtsAire', models.DecimalField(decimal_places=2, max_digits=3)),
                ('horasOxigeno', models.DecimalField(decimal_places=2, max_digits=3)),
                ('horasAire', models.DecimalField(decimal_places=2, max_digits=3)),
                ('totalLtsoxigeno', models.DecimalField(decimal_places=2, max_digits=3)),
                ('totalLtsAire', models.DecimalField(decimal_places=2, max_digits=3)),
                ('totalMetrocubicoOxigeno', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoria56', to='usuarios.Usuarios')),
                ('tipoDoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta')),
            ],
        ),
    ]
