# Generated by Django 2.1.15 on 2024-07-18 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0003_auto_20240702_1521'),
        ('usuarios', '0003_auto_20240710_1531'),
        ('facturacion', '0006_conveniospaciente_conveniospacienteingresos'),
        ('clinico', '0026_imhaloterapia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antibiotico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consecAdmision', models.IntegerField(default=0)),
                ('folio', models.IntegerField(default=0)),
                ('fechaSolicitud', models.DateTimeField()),
                ('fechaInicio', models.DateTimeField()),
                ('profilaxis', models.CharField(blank=True, max_length=10, null=True)),
                ('ttoEmpirico', models.CharField(blank=True, max_length=10, null=True)),
                ('ttoetiologico', models.CharField(blank=True, max_length=10, null=True)),
                ('ampliacionTto', models.CharField(blank=True, max_length=10, null=True)),
                ('cambioEsquema', models.CharField(blank=True, max_length=10, null=True)),
                ('saludPublica', models.CharField(blank=True, max_length=10, null=True)),
                ('dxInfeccion', models.CharField(blank=True, max_length=1000, null=True)),
                ('germenAislado', models.CharField(blank=True, max_length=1000, null=True)),
                ('fechaVigencia', models.DateTimeField()),
                ('fallaRenal', models.CharField(blank=True, max_length=10, null=True)),
                ('fallaHepatica', models.CharField(blank=True, max_length=10, null=True)),
                ('infeccionSevera', models.CharField(blank=True, max_length=10, null=True)),
                ('inmunoSupresion', models.CharField(blank=True, max_length=10, null=True)),
                ('aprobado', models.CharField(blank=True, max_length=15, null=True)),
                ('prescripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('protocolo', models.CharField(blank=True, max_length=1000, null=True)),
                ('noProtocolo', models.CharField(blank=True, max_length=1000, null=True)),
                ('ajustadoCultivo', models.CharField(blank=True, max_length=1000, null=True)),
                ('ajustadoDosiRenal', models.CharField(blank=True, max_length=1000, null=True)),
                ('autInfectologia', models.CharField(blank=True, max_length=2, null=True)),
                ('observacionEpidemilogia', models.CharField(blank=True, max_length=10000, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoria34', to='usuarios.Usuarios')),
                ('suministro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sumins03', to='facturacion.Suministros')),
                ('tipoDoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta')),
            ],
        ),
    ]
