# Generated by Django 2.1.15 on 2024-07-18 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20240710_1531'),
        ('planta', '0003_auto_20240702_1521'),
        ('facturacion', '0006_conveniospaciente_conveniospacienteingresos'),
        ('clinico', '0027_antibiotico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consecAdmision', models.IntegerField(default=0)),
                ('folio', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField()),
                ('orden', models.IntegerField(default=0)),
                ('concentracion', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('dosisCantidad', models.DecimalField(decimal_places=3, max_digits=20)),
                ('frecuenciaCantidad', models.DecimalField(decimal_places=0, max_digits=2)),
                ('nota', models.CharField(blank=True, max_length=5000)),
                ('cantidadSolicitada', models.DecimalField(decimal_places=0, max_digits=20)),
                ('cantidadEntregada', models.DecimalField(decimal_places=0, max_digits=20)),
                ('cantidadDispensada', models.DecimalField(decimal_places=0, max_digits=20)),
                ('cantidadAplicada', models.DecimalField(decimal_places=0, max_digits=20)),
                ('cantidadDevuelta', models.DecimalField(decimal_places=0, max_digits=20)),
                ('cantidadSaldoIni', models.DecimalField(decimal_places=0, max_digits=20)),
                ('cantidadsaldoFinal', models.DecimalField(decimal_places=0, max_digits=20)),
                ('cantidadfacturada', models.DecimalField(decimal_places=0, max_digits=20)),
                ('nopos', models.CharField(blank=True, max_length=1, null=True)),
                ('estadoMedicamento', models.CharField(blank=True, max_length=1, null=True)),
                ('horarioDosis', models.CharField(blank=True, max_length=200, null=True)),
                ('dosisUnica', models.DecimalField(decimal_places=0, max_digits=10)),
                ('dosisRescate', models.CharField(blank=True, max_length=200, null=True)),
                ('dosisProfilaxis', models.CharField(blank=True, max_length=200, null=True)),
                ('dosisAdelanto', models.CharField(blank=True, max_length=200, null=True)),
                ('urgente', models.CharField(blank=True, max_length=1, null=True)),
                ('dosificacion', models.CharField(blank=True, max_length=2000, null=True)),
                ('antibiotico', models.CharField(blank=True, max_length=1, null=True)),
                ('fechaSuspension', models.DateTimeField()),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoria89', to='usuarios.Usuarios')),
                ('dosisUnidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.UnidadesDeMedidaDosis')),
                ('frecuenciaUnidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.FrecuenciasAplicacion')),
                ('suministro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Suministros')),
                ('tipoDoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta')),
            ],
        ),
    ]
