# Generated by Django 2.1.15 on 2024-07-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0029_auto_20240719_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticos',
            name='habilitadoMipres',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
