# Generated by Django 2.1.15 on 2024-07-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0030_diagnosticos_habilitadomipres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticos',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='diagnosticos',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
    ]
