# Generated by Django 2.1.15 on 2024-07-25 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20240710_1531'),
        ('facturacion', '0007_eapb'),
        ('planta', '0003_auto_20240702_1521'),
        ('clinico', '0031_auto_20240719_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenesLaboratorio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoCups', models.CharField(default=0, max_length=20)),
                ('nombre', models.CharField(max_length=300)),
                ('edadIni', models.IntegerField()),
                ('edadFin', models.IntegerField()),
                ('citaControl', models.CharField(default=0, max_length=1)),
                ('codigoRips', models.CharField(default=0, max_length=6)),
                ('autorizar', models.CharField(default=0, max_length=1)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('TiposExamen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposExamen')),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Conceptos')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenesNoQx',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoCups', models.CharField(default=0, max_length=20)),
                ('nombre', models.CharField(max_length=300)),
                ('edadIni', models.IntegerField()),
                ('edadFin', models.IntegerField()),
                ('citaControl', models.CharField(default=0, max_length=1)),
                ('codigoRips', models.CharField(default=0, max_length=6)),
                ('autorizar', models.CharField(default=0, max_length=1)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('TiposExamen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposExamen')),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Conceptos')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenesRadiologia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoCups', models.CharField(default=0, max_length=20)),
                ('nombre', models.CharField(max_length=300)),
                ('edadIni', models.IntegerField()),
                ('edadFin', models.IntegerField()),
                ('citaControl', models.CharField(default=0, max_length=1)),
                ('codigoRips', models.CharField(default=0, max_length=6)),
                ('autorizar', models.CharField(default=0, max_length=1)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('TiposExamen', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposExamen')),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Conceptos')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenesTerapias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoCups', models.CharField(default=0, max_length=20)),
                ('nombre', models.CharField(max_length=3000)),
                ('edadIni', models.IntegerField()),
                ('edadFin', models.IntegerField()),
                ('citaControl', models.CharField(default=0, max_length=1)),
                ('codigoRips', models.CharField(default=0, max_length=6)),
                ('autorizar', models.CharField(default=0, max_length=1)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('TiposExamen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposExamen')),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Conceptos')),
            ],
        ),
        migrations.CreateModel(
            name='TiposRadiologia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='antibiotico',
            name='consecAdmision',
        ),
        migrations.RemoveField(
            model_name='antibiotico',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='antibiotico',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='antibiotico',
            name='tipoDoc',
        ),
        migrations.RemoveField(
            model_name='historiaexamenes',
            name='historiaExamenesCabezote',
        ),
        migrations.RemoveField(
            model_name='historiaexamenes',
            name='procedimientos',
        ),
        migrations.RemoveField(
            model_name='historialantecedentes',
            name='consecAdmision',
        ),
        migrations.RemoveField(
            model_name='historialantecedentes',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='historialantecedentes',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='historialantecedentes',
            name='tipoDoc',
        ),
        migrations.RemoveField(
            model_name='historialdiagnosticos',
            name='historialDiagnosticosCabezote',
        ),
        migrations.RemoveField(
            model_name='imhaloterapia',
            name='consecAdmision',
        ),
        migrations.RemoveField(
            model_name='imhaloterapia',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='imhaloterapia',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='imhaloterapia',
            name='tipoDoc',
        ),
        migrations.RemoveField(
            model_name='incapacidades',
            name='consecAdmision',
        ),
        migrations.RemoveField(
            model_name='incapacidades',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='incapacidades',
            name='tipoDoc',
        ),
        migrations.RemoveField(
            model_name='interconsultas',
            name='consecAdmision',
        ),
        migrations.RemoveField(
            model_name='interconsultas',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='interconsultas',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='interconsultas',
            name='tipoDoc',
        ),
        migrations.RemoveField(
            model_name='medicamentos',
            name='consecAdmision',
        ),
        migrations.RemoveField(
            model_name='medicamentos',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='medicamentos',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='medicamentos',
            name='tipoDoc',
        ),
        migrations.RemoveField(
            model_name='oxigeno',
            name='consecAdmision',
        ),
        migrations.RemoveField(
            model_name='oxigeno',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='oxigeno',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='oxigeno',
            name='tipoDoc',
        ),
        migrations.RemoveField(
            model_name='revisionpacientessistemas',
            name='consecAdmision',
        ),
        migrations.RemoveField(
            model_name='revisionpacientessistemas',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='revisionpacientessistemas',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='revisionpacientessistemas',
            name='tipoDoc',
        ),
        migrations.RemoveField(
            model_name='signosvitales',
            name='consecAdmision',
        ),
        migrations.RemoveField(
            model_name='signosvitales',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='signosvitales',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='signosvitales',
            name='tipoDoc',
        ),
        migrations.RemoveField(
            model_name='trasfusiones',
            name='consecAdmision',
        ),
        migrations.RemoveField(
            model_name='trasfusiones',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='trasfusiones',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='trasfusiones',
            name='tipoDoc',
        ),
        migrations.AddField(
            model_name='antibiotico',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag28', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='hallazgos',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag13', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='anulado',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='consecutivo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='facturado',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='fechaPreliminar1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='fechaPreliminar2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='fechaPreliminar3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='fechaToma',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='interpretacion1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='interpretacion2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='interpretacion3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='medicoInterpretacion1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medInterpreta1', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='medicoInterpretacion2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medInterpreta2', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='medicoInterpretacion3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medInterpreta3', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='medicoReporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medReporte', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='opinion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='preliminar1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='preliminar2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='preliminar3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='resultado',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='rutaImagen',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='rutaVideo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='usuarioAnula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioAnula1', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='usuarioToma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioToma1', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='usuaroRegistra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioRegistra1', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='historialantecedentes',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag9', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='historialdiagnosticos',
            name='consecutivo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialdiagnosticos',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag8', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='historialdiagnosticos',
            name='observaciones',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='imhaloterapia',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag27', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='incapacidades',
            name='historia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag10', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='interconsultas',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag11', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='historia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag12', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='oxigeno',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag26', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='revisionpacientessistemas',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag24', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag23', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='trasfusiones',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag25', to='clinico.Historia'),
        ),
        migrations.AlterField(
            model_name='especialidadesmedicos',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioRegistroPlanta', to='planta.Planta'),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='TiposExamen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='historiaexamenescabezote',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Historia'),
        ),
        migrations.AlterField(
            model_name='historialantecedentes',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.Usuarios'),
        ),
        migrations.AlterField(
            model_name='historialdiagnosticos',
            name='diagnosticos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dxPpal', to='clinico.Diagnosticos'),
        ),
        migrations.AlterField(
            model_name='historialdiagnosticos',
            name='tiposDiagnostico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tiposDiagnostico', to='clinico.TiposDiagnostico'),
        ),
        migrations.AlterField(
            model_name='historialdiagnosticoscabezote',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag', to='usuarios.Usuarios'),
        ),
        migrations.AlterField(
            model_name='historialdiagnosticoscabezote',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AlterField(
            model_name='historiaresultados',
            name='dependenciasRealizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Dependencias'),
        ),
        migrations.AlterField(
            model_name='historiaresultados',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaResul', to='usuarios.Usuarios'),
        ),
        migrations.AlterField(
            model_name='historiaresultados',
            name='estadoExamenes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.EstadoExamenes'),
        ),
        migrations.AlterField(
            model_name='historiaresultados',
            name='examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Examenes'),
        ),
        migrations.AlterField(
            model_name='historiaresultados',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AlterField(
            model_name='incapacidades',
            name='dependenciasRealizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Dependencias'),
        ),
        migrations.AlterField(
            model_name='incapacidades',
            name='diagnosticos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Diagnosticos'),
        ),
        migrations.AlterField(
            model_name='incapacidades',
            name='tiposIncapacidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposIncapacidad'),
        ),
        migrations.AlterField(
            model_name='interconsultas',
            name='diagnosticos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Diagnosticos'),
        ),
        migrations.AlterField(
            model_name='interconsultas',
            name='estadosInterconsulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.EstadosInterconsulta'),
        ),
        migrations.AlterField(
            model_name='interconsultas',
            name='plantaConsultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Centros'),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Ciudades'),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Departamentos'),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='especialidades',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Especialidades'),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='planta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AlterUniqueTogether(
            name='historia',
            unique_together={('tipoDoc', 'documento', 'consecAdmision', 'folio')},
        ),
        migrations.AddField(
            model_name='examenesradiologia',
            name='tipoRadiologia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposRadiologia'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='examenesLaboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.ExamenesLaboratorio'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='examenesNoQx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.ExamenesNoQx'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='examenesRadiologia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.ExamenesRadiologia'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='examenesTerapias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.ExamenesTerapias'),
        ),
    ]
