# Generated by Django 2.1.15 on 2024-07-25 12:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20240710_1531'),
        ('clinico', '0032_auto_20240725_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaexamenescabezote',
            name='fechaRegistro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='historiaexamenescabezote',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.Usuarios'),
        ),
        migrations.AlterField(
            model_name='historiaexamenescabezote',
            name='historia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.Historia'),
        ),
    ]
