# Generated by Django 2.1.15 on 2024-08-29 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_auto_20240828_1410'),
        ('clinico', '0033_auto_20240725_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenes',
            name='codigo',
        ),
        migrations.AddField(
            model_name='examenes',
            name='autorizar',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='examenes',
            name='citaControl',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='examenes',
            name='codigoCups',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='examenes',
            name='codigoRips',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='examenes',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Conceptos'),
        ),
        migrations.AddField(
            model_name='examenes',
            name='edadFin',
            field=models.IntegerField(blank=True, default=120),
        ),
        migrations.AddField(
            model_name='examenes',
            name='edadIni',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='examenes',
            name='estadoReg',
            field=models.CharField(default='A', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='examenes',
            name='tipoRadiologia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposRadiologia'),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
    ]
