# Generated by Django 2.1.15 on 2024-08-29 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0034_auto_20240829_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exameneslaboratorio',
            name='TiposExamen',
        ),
        migrations.RemoveField(
            model_name='exameneslaboratorio',
            name='concepto',
        ),
        migrations.AlterField(
            model_name='historiaexamenes',
            name='examenesLaboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Examenes'),
        ),
        migrations.DeleteModel(
            name='ExamenesLaboratorio',
        ),
    ]
