# Generated by Django 2.1.15 on 2024-08-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0038_auto_20240829_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenes',
            name='solicitaEnfermeria',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1),
        ),
    ]
