# Generated by Django 2.1.15 on 2024-08-29 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0039_examenes_solicitaenfermeria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaexamenes',
            name='examenesLaboratorio',
        ),
        migrations.RemoveField(
            model_name='historiaexamenes',
            name='examenesNoQx',
        ),
        migrations.RemoveField(
            model_name='historiaexamenes',
            name='examenesRadiologia',
        ),
        migrations.RemoveField(
            model_name='historiaexamenes',
            name='examenesTerapias',
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='tiposExamen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='historiaexamenes',
            name='observaciones',
            field=models.CharField(max_length=200),
        ),
    ]
