# Generated by Django 2.1.15 on 2024-08-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0040_auto_20240829_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaexamenes',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
