# Generated by Django 2.1.15 on 2024-08-29 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0041_auto_20240829_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaexamenescabezote',
            name='historia',
        ),
        migrations.RemoveField(
            model_name='historiaexamenescabezote',
            name='tiposExamen',
        ),
        migrations.RemoveField(
            model_name='historiaexamenescabezote',
            name='usuarioRegistro',
        ),
        migrations.DeleteModel(
            name='HistoriaExamenesCabezote',
        ),
    ]
