# Generated by Django 2.1.15 on 2024-09-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0044_auto_20240902_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='indiceMortalidad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
