# Generated by Django 2.1.15 on 2024-09-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0045_auto_20240902_1629'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examenes',
            unique_together={('codigoCups',)},
        ),
    ]
