# Generated by Django 2.1.15 on 2024-09-05 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0046_auto_20240904_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antecedentes',
            name='tiposAntecedente',
        ),
        migrations.RemoveField(
            model_name='historialantecedentes',
            name='antecedentes',
        ),
        migrations.DeleteModel(
            name='Antecedentes',
        ),
    ]
