# Generated by Django 2.1.15 on 2024-09-06 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0047_auto_20240905_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposInterconsulta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='interconsultas',
            name='plantaConsultado',
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='fechaReporte',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interconsultas',
            name='especialidadConsulta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.Especialidades'),
        ),
        migrations.AddField(
            model_name='interconsultas',
            name='medicoConsulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Medicos'),
        ),
        migrations.AddField(
            model_name='interconsultas',
            name='medicoConsultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='med22', to='clinico.Medicos'),
        ),
        migrations.AlterField(
            model_name='interconsultas',
            name='especialidadConsultada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='espe22', to='clinico.Especialidades'),
        ),
        migrations.AlterField(
            model_name='interconsultas',
            name='respuestaConsulta',
            field=models.CharField(max_length=800),
        ),
        migrations.AddField(
            model_name='interconsultas',
            name='tipoInterconsulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposInterconsulta'),
        ),
    ]
