# Generated by Django 2.1.15 on 2024-09-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0049_auto_20240909_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incapacidades',
            name='dependenciasRealizado',
        ),
        migrations.AddField(
            model_name='incapacidades',
            name='descripcion',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
