# Generated by Django 2.1.15 on 2024-09-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0050_auto_20240909_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incapacidades',
            name='fecha',
        ),
    ]
