# Generated by Django 2.1.15 on 2024-09-09 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0051_remove_incapacidades_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incapacidades',
            name='desdeFecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='incapacidades',
            name='hastaFecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
