# Generated by Django 2.1.15 on 2024-09-09 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0052_auto_20240909_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incapacidades',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag10', to='clinico.Historia'),
        ),
    ]
