# Generated by Django 2.1.15 on 2024-09-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0053_auto_20240909_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='incapacidades',
            name='numDias',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
