# Generated by Django 2.1.15 on 2024-09-10 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0054_incapacidades_numdias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incapacidades',
            old_name='diagnosticos',
            new_name='diagnosticosIncapacidad',
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
