# Generated by Django 2.1.15 on 2024-09-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0058_auto_20240910_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signosvitales',
            name='apache',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='cuna',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='frecCardiaca',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='frecRespiratoria',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='glasgow',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='glasgowMotora',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='glasgowOcular',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='glasgowVerbal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='glucometria',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='ic',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='observacion',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='pvc',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='saturacion',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='tensionADiastolica',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='tensionAMedia',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='tensionASistolica',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
