# Generated by Django 2.1.15 on 2024-09-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0059_auto_20240910_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signosvitales',
            name='temperatura',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
