# Generated by Django 2.1.15 on 2024-09-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0060_auto_20240910_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientedci',
            name='codigoMipres',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='formasfarmaceuticas',
            name='codigoMipres',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='frecuenciasaplicacion',
            name='codigoMipres',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='indicacionesespeciales',
            name='codigoMipres',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='medicamentosdci',
            name='codigoMipres',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='presentacion',
            name='codigoMipres',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='productosnutricion',
            name='codigoMipres',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tiposdispositivomedico',
            name='codigoMipres',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tiposmedicamento',
            name='codigoMipres',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tiposproductosnutricion',
            name='codigoMipres',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='unidadesdemedida',
            name='codigoMipres',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='unidadesdemedidadosis',
            name='codigoMipres',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='viasadministracion',
            name='codigoMipres',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
