# Generated by Django 2.1.15 on 2024-09-12 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0003_auto_20240702_1521'),
        ('clinico', '0063_auto_20240912_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaRevisionSistemas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observacion', models.CharField(blank=True, max_length=5000)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('historia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaRev1', to='clinico.Historia')),
                ('revisionSistemas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.RevisionSistemas')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta')),
            ],
        ),
    ]
