# Generated by Django 2.1.15 on 2024-09-12 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0064_historiarevisionsistemas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisionpacientessistemas',
            name='historia',
        ),
        migrations.RemoveField(
            model_name='revisionpacientessistemas',
            name='revisionSistemas',
        ),
        migrations.RemoveField(
            model_name='revisionpacientessistemas',
            name='usuarioRegistro',
        ),
        migrations.DeleteModel(
            name='RevisionPacientesSistemas',
        ),
    ]
