# Generated by Django 2.1.15 on 2024-09-12 09:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0003_auto_20240702_1521'),
        ('clinico', '0065_auto_20240912_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaSignosVitales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('frecCardiaca', models.CharField(blank=True, max_length=5, null=True)),
                ('frecRespiratoria', models.CharField(blank=True, max_length=5, null=True)),
                ('tensionADiastolica', models.CharField(blank=True, max_length=5, null=True)),
                ('tensionASistolica', models.CharField(blank=True, max_length=5, null=True)),
                ('tensionAMedia', models.CharField(blank=True, max_length=5, null=True)),
                ('temperatura', models.CharField(blank=True, max_length=5, null=True)),
                ('saturacion', models.CharField(blank=True, max_length=5, null=True)),
                ('glucometria', models.CharField(blank=True, max_length=5, null=True)),
                ('glasgow', models.CharField(blank=True, max_length=5, null=True)),
                ('apache', models.CharField(blank=True, max_length=5, null=True)),
                ('pvc', models.CharField(blank=True, max_length=5, null=True)),
                ('cuna', models.CharField(blank=True, max_length=5, null=True)),
                ('ic', models.CharField(blank=True, max_length=5, null=True)),
                ('glasgowOcular', models.CharField(blank=True, max_length=5, null=True)),
                ('glasgowVerbal', models.CharField(blank=True, max_length=5, null=True)),
                ('glasgowMotora', models.CharField(blank=True, max_length=5, null=True)),
                ('observacion', models.CharField(blank=True, max_length=5000, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('historia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaSig2', to='clinico.Historia')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta')),
            ],
        ),
    ]
