# Generated by Django 2.1.15 on 2024-09-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0067_codigosatc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedientedci',
            name='formaFarmaceutica',
        ),
    ]
