# Generated by Django 2.1.15 on 2024-09-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0068_remove_expedientedci_formafarmaceutica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formasfarmaceuticas',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
