# Generated by Django 2.1.15 on 2024-09-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0069_auto_20240912_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenes',
            name='centroCosto',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='examenes',
            name='cita1Vez',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='examenes',
            name='consentimientoInformado',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='examenes',
            name='cuentaContable',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='examenes',
            name='cupsCategoria',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='examenes',
            name='cupsGrupo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='examenes',
            name='cupsSubgrupo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='examenes',
            name='distribucionTerceros',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='examenes',
            name='duracion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='examenes',
            name='finalidad',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='examenes',
            name='manejaInterfaz',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='examenes',
            name='nivelAtencion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='examenes',
            name='resolucion1132',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='autorizar',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='codigoRips',
            field=models.CharField(blank=True, default=0, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='edadFin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='edadIni',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='antibioticos',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('N', 'N')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='inmovilizacion',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('N', 'N')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='interconsulta',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('N', 'N')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='irritacion',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('N', 'N')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='llenadoCapilar',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('N', 'N')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='monitoreo',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('N', 'N')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='movilidadLimitada',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('N', 'N')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='nauseas',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('N', 'N')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='neurologia',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('N', 'N')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='notaAclaratoria',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('N', 'N')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='pulsos',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('N', 'N')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='retiroPuntos',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('N', 'N')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='vomito',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('N', 'N')], max_length=1, null=True),
        ),
    ]
