# Generated by Django 2.1.15 on 2024-09-16 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0020_auto_20240916_1644'),
        ('clinico', '0070_auto_20240916_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenes',
            name='grupoQx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.GruposQx'),
        ),
    ]
