# Generated by Django 2.1.15 on 2024-09-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0072_auto_20240917_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examenes',
            old_name='numeroUvr',
            new_name='cantidadUvr',
        ),
        migrations.AddField(
            model_name='examenes',
            name='honorarios',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
