# Generated by Django 2.1.15 on 2024-09-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0073_auto_20240917_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formasfarmaceuticas',
            name='codigoMipres',
        ),
        migrations.RemoveField(
            model_name='formasfarmaceuticas',
            name='habilitadoMipres',
        ),
        migrations.RemoveField(
            model_name='frecuenciasaplicacion',
            name='codigoMipres',
        ),
        migrations.RemoveField(
            model_name='frecuenciasaplicacion',
            name='habilitadoMipres',
        ),
        migrations.RemoveField(
            model_name='presentacion',
            name='codigoMipres',
        ),
        migrations.RemoveField(
            model_name='presentacion',
            name='habilitadoMipres',
        ),
        migrations.RemoveField(
            model_name='unidadesdemedida',
            name='codigoMipres',
        ),
        migrations.RemoveField(
            model_name='unidadesdemedida',
            name='habilitadoMipres',
        ),
        migrations.RemoveField(
            model_name='unidadesdemedidadosis',
            name='codigoMipres',
        ),
        migrations.RemoveField(
            model_name='unidadesdemedidadosis',
            name='habilitadoMipres',
        ),
    ]
