# Generated by Django 2.1.15 on 2024-09-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0074_auto_20240917_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiamedicamentos',
            name='cantidadOrdenada',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historiamedicamentos',
            name='diasTratamiento',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedicamentos',
            name='cantidadAplicada',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedicamentos',
            name='cantidadDevuelta',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedicamentos',
            name='cantidadDispensada',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedicamentos',
            name='cantidadEntregada',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedicamentos',
            name='cantidadSolicitada',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedicamentos',
            name='cantidadfacturada',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
