# Generated by Django 2.1.15 on 2024-09-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0075_auto_20240917_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiamedicamentos',
            name='dosisUnica',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedicamentos',
            name='fechaSuspension',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
