# Generated by Django 2.1.15 on 2024-09-19 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0076_auto_20240917_1714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incapacidades',
            new_name='HistorialIncapacidades',
        ),
        migrations.RenameModel(
            old_name='Interconsultas',
            new_name='HistorialInterconsultas',
        ),
    ]
