# Generated by Django 2.1.15 on 2024-09-25 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0078_auto_20240919_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenesRasgos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoCups', models.CharField(blank=True, max_length=20)),
                ('nombre', models.CharField(max_length=80)),
                ('valor', models.CharField(max_length=20)),
                ('unidad', models.CharField(max_length=20)),
                ('minimo', models.CharField(max_length=20)),
                ('maximo', models.CharField(max_length=20)),
                ('observacion', models.CharField(max_length=255)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('tiposExamen', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposExamen')),
            ],
        ),
    ]
