# Generated by Django 2.1.15 on 2024-09-25 07:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0080_auto_20240925_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenesrasgos',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='examenesrasgos',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='historiaresultados',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='historiaresultados',
            name='consecAdmision',
        ),
        migrations.RemoveField(
            model_name='historiaresultados',
            name='consecResultados',
        ),
        migrations.RemoveField(
            model_name='historiaresultados',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='historiaresultados',
            name='examen',
        ),
        migrations.RemoveField(
            model_name='historiaresultados',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='historiaresultados',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='historiaresultados',
            name='interpretacion',
        ),
        migrations.RemoveField(
            model_name='historiaresultados',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='historiaresultados',
            name='rutaArchivo',
        ),
        migrations.RemoveField(
            model_name='historiaresultados',
            name='rutaVideo',
        ),
        migrations.RemoveField(
            model_name='historiaresultados',
            name='tipoDoc',
        ),
        migrations.RemoveField(
            model_name='historiaresultados',
            name='tiposExamen',
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='consecResultado',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='examenesRasgos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.ExamenesRasgos'),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='fechaResultado',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='fechaServicio',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='historiaExamenes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.HistoriaExamenes'),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='valor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
