# Generated by Django 2.1.15 on 2024-09-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0082_auto_20240927_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenes',
            name='codigoCups',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
