# Generated by Django 2.1.15 on 2024-09-27 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0084_auto_20240927_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiamedicamentos',
            name='cantidadDispensada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsUnidadUpr'),
        ),
    ]
