# Generated by Django 2.1.15 on 2024-09-30 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0085_auto_20240927_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenes',
            name='grupoQx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifas.GruposQx'),
        ),
    ]
