# Generated by Django 2.1.15 on 2024-10-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0086_auto_20240930_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaresultados',
            name='historia',
        ),
    ]
