# Generated by Django 2.1.15 on 2024-10-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0087_remove_historiaresultados_historia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaresultados',
            name='dependenciasRealizado',
        ),
    ]
