# Generated by Django 2.1.15 on 2024-10-09 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0012_auto_20240812_1010'),
        ('clinico', '0088_remove_historiaresultados_dependenciasrealizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaexamenes',
            name='dependenciasRealizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Dependencias'),
        ),
        migrations.AlterField(
            model_name='historia',
            name='dependenciasRealizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Dependencias'),
        ),
    ]
