# Generated by Django 2.1.15 on 2024-10-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0089_auto_20241009_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaresultados',
            name='estadoExamenes',
        ),
    ]
