# Generated by Django 2.1.15 on 2024-10-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0090_remove_historiaresultados_estadoexamenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenes',
            name='cupsSubCategoria',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
