# Generated by Django 2.1.15 on 2024-10-16 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0012_liquidacionhonorarios_descripcion'),
        ('clinico', '0091_examenes_cupssubcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenes',
            name='uvrAño',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Uvr105', to='tarifas.Uvr'),
        ),
    ]
