# Generated by Django 2.1.15 on 2024-10-23 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0003_auto_20240702_1521'),
        ('clinico', '0092_examenes_uvraño'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOxigenacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('flujoLtsOxigeno', models.DecimalField(decimal_places=2, max_digits=3)),
                ('flujoLtsAire', models.DecimalField(decimal_places=2, max_digits=3)),
                ('codFacturar', models.CharField(blank=True, max_length=30)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta')),
            ],
        ),
        migrations.RemoveField(
            model_name='oxigeno',
            name='flujoLtsAire',
        ),
        migrations.RemoveField(
            model_name='oxigeno',
            name='flujoLtsOxigeno',
        ),
        migrations.AlterField(
            model_name='oxigeno',
            name='tipoOxigenacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipoOxigenacion01', to='clinico.TipoOxigenacion'),
        ),
    ]
