# Generated by Django 2.1.15 on 2024-10-23 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0003_auto_20240702_1521'),
        ('clinico', '0093_auto_20241023_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaOxigeno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFinal', models.DateTimeField()),
                ('aire', models.CharField(blank=True, max_length=1)),
                ('saturacionOxigeno', models.DecimalField(decimal_places=2, max_digits=3)),
                ('horasOxigeno', models.DecimalField(decimal_places=2, max_digits=3)),
                ('horasAire', models.DecimalField(decimal_places=2, max_digits=3)),
                ('totalLtsoxigeno', models.DecimalField(decimal_places=2, max_digits=3)),
                ('totalLtsAire', models.DecimalField(decimal_places=2, max_digits=3)),
                ('totalMetrocubicoOxigeno', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('historia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag29', to='clinico.Historia')),
                ('tipoOxigenacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipoOxigenacion02', to='clinico.TipoOxigenacion')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta')),
            ],
        ),
    ]
