# Generated by Django 2.1.15 on 2024-10-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0094_historiaoxigeno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oxigeno',
            name='historia',
        ),
        migrations.RemoveField(
            model_name='oxigeno',
            name='tipoOxigenacion',
        ),
        migrations.RemoveField(
            model_name='oxigeno',
            name='usuarioRegistro',
        ),
        migrations.DeleteModel(
            name='Oxigeno',
        ),
    ]
