# Generated by Django 2.1.15 on 2024-07-18 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_auto_20240710_1531'),
        ('planta', '0003_auto_20240702_1521'),
        ('contratacion', '0003_convenios'),
        ('facturacion', '0006_conveniospaciente_conveniospacienteingresos'),
        ('clinico', '0021_auto_20240718_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consecAdmision', models.IntegerField(default=0)),
                ('tipoAtencion', models.CharField(default='A', editable=False, max_length=20)),
                ('anamnesis', models.CharField(blank=True, max_length=2000, null=True)),
                ('exaFisico', models.CharField(blank=True, max_length=2000, null=True)),
                ('exaDiagnostico', models.CharField(blank=True, max_length=2000, null=True)),
                ('tratamiento', models.CharField(default='A', editable=False, max_length=2000)),
                ('motivoReferencia', models.CharField(blank=True, max_length=2000, null=True)),
                ('otroMotivo', models.CharField(blank=True, max_length=2000, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.UsuariosContacto')),
                ('convenio1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convenio22', to='contratacion.Convenios')),
                ('convenio2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convenio23', to='contratacion.Convenios')),
                ('cups1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups28', to='facturacion.Cups')),
                ('cups2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups27', to='facturacion.Cups')),
                ('cups3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups26', to='facturacion.Cups')),
                ('cups4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups25', to='facturacion.Cups')),
                ('cups5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups24', to='facturacion.Cups')),
                ('cups6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups23', to='facturacion.Cups')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoria9', to='usuarios.Usuarios')),
                ('dxEgreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Diagnosticos')),
                ('dxIngreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dx27', to='clinico.Diagnosticos')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups22', to='planta.Planta')),
                ('regimerReferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dx26', to='clinico.Regimenes')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Servicios')),
                ('tipoDoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta')),
            ],
        ),
    ]
