# Generated by Django 2.1.15 on 2024-09-16 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencia',
            name='cups1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups28', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='cups2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups27', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='cups3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups26', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='cups4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups25', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='cups5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups24', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='cups6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups23', to='clinico.TiposExamen'),
        ),
    ]
