# Generated by Django 2.1.15 on 2024-09-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivosglosas',
            name='nombre',
            field=models.CharField(max_length=600),
        ),
    ]
