# Generated by Django 2.1.15 on 2024-09-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0002_auto_20240912_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivosglosas',
            name='descripcion',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='motivosglosas',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
