# Generated by Django 2.1.15 on 2024-09-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0003_auto_20240912_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormasPagos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
    ]
