# Generated by Django 2.1.15 on 2024-09-20 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0004_formaspagos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='nombre',
        ),
    ]
