# Generated by Django 2.1.15 on 2024-09-20 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0005_remove_pagos_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='formaPago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.FormasPagos'),
        ),
    ]
