# Generated by Django 2.1.15 on 2024-09-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0006_pagos_formapago'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposNotas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
    ]
