# Generated by Django 2.1.15 on 2024-11-14 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0056_auto_20241108_1500'),
        ('cartera', '0008_glosas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='facturaAplicada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Facturacion'),
        ),
    ]
