# Generated by Django 2.1.15 on 2024-11-21 08:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0057_auto_20241121_0806'),
        ('cartera', '0009_pagos_facturaaplicada'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagosFacturas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valorAplicado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('facturaAplicada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Facturacion')),
            ],
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='facturaAplicada',
        ),
        migrations.AddField(
            model_name='pagos',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='pagos',
            name='totalAplicado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pagosfacturas',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.Pagos'),
        ),
    ]
