# Generated by Django 2.1.15 on 2024-11-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0011_auto_20241121_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='valorEnCurso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
