# Generated by Django 2.1.15 on 2024-07-02 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0005_auto_20240702_1521'),
        ('planta', '0002_auto_20240628_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilesplanta',
            name='planta',
        ),
        migrations.RemoveField(
            model_name='perfilesplanta',
            name='sedesClinica',
        ),
        migrations.RemoveField(
            model_name='perfilesplanta',
            name='tiposPlanta',
        ),
        migrations.AddField(
            model_name='planta',
            name='tiposPlanta',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.TiposPlanta'),
        ),
        migrations.DeleteModel(
            name='PerfilesPlanta',
        ),
    ]
