# Generated by Django 2.1.15 on 2024-07-02 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0002_auto_20240628_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependenciasactual',
            name='fecha',
        ),
        migrations.AddField(
            model_name='dependenciasactual',
            name='fechaLiberacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dependenciasactual',
            name='fechaOcupacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historialdependencias',
            name='disponibilidad',
            field=models.CharField(choices=[('L', 'LIBRE'), ('O', 'OCUPADA')], default='L', max_length=1),
        ),
    ]
