# Generated by Django 2.1.15 on 2024-07-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0003_auto_20240702_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subserviciossedes',
            old_name='servicios',
            new_name='serviciosSedes',
        ),
        migrations.RenameField(
            model_name='subserviciossedes',
            old_name='subServicios',
            new_name='subServiciosSedes',
        ),
        migrations.AlterUniqueTogether(
            name='subserviciossedes',
            unique_together={('sedesClinica', 'serviciosSedes', 'subServiciosSedes')},
        ),
    ]
