# Generated by Django 2.1.15 on 2024-07-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0004_auto_20240702_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencias',
            name='disponibilidad',
            field=models.CharField(choices=[('L', 'LIBRE'), ('O', 'OCUPADA')], default='L', max_length=1),
        ),
    ]
