# Generated by Django 2.1.15 on 2024-07-05 09:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0005_dependencias_disponibilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('localidadCodigoDian', models.CharField(default='', max_length=15)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('municipioCodigoDian', models.CharField(default='', max_length=15)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('paisCodigoDian', models.CharField(default='', max_length=15)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='departamentos',
            name='departamentoCodigoDian',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='centros',
            name='departamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Departamentos'),
        ),
        migrations.AlterField(
            model_name='ciudades',
            name='departamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciudades', to='sitios.Departamentos'),
        ),
        migrations.AlterField(
            model_name='dependencias',
            name='dependenciasTipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.DependenciasTipo'),
        ),
        migrations.AlterField(
            model_name='dependencias',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.SedesClinica'),
        ),
        migrations.AlterField(
            model_name='dependencias',
            name='serviciosSedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serviciosSedes1', to='sitios.ServiciosSedes'),
        ),
        migrations.AlterField(
            model_name='dependencias',
            name='subServiciosSedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.SubServiciosSedes'),
        ),
        migrations.AlterField(
            model_name='dependenciasactual',
            name='dependencias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Dependencias'),
        ),
        migrations.AlterField(
            model_name='dependenciasactual',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoDepAct', to='usuarios.Usuarios'),
        ),
        migrations.AlterField(
            model_name='dependenciasactual',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AlterField(
            model_name='dependenciasactual',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AlterField(
            model_name='historialdependencias',
            name='dependencias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Dependencias'),
        ),
        migrations.AlterField(
            model_name='historialdependencias',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentohistorialDep', to='usuarios.Usuarios'),
        ),
        migrations.AlterField(
            model_name='historialdependencias',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AlterField(
            model_name='historialdependencias',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AlterField(
            model_name='sedesclinica',
            name='departamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Departamentos'),
        ),
        migrations.AlterField(
            model_name='serviciossedes',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.SedesClinica'),
        ),
        migrations.AlterField(
            model_name='serviciossedes',
            name='servicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Servicios'),
        ),
        migrations.AlterField(
            model_name='subserviciossedes',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='municipios',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Departamentos'),
        ),
        migrations.AddField(
            model_name='localidades',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Municipios'),
        ),
        migrations.AddField(
            model_name='departamentos',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Paises'),
        ),
    ]
