# Generated by Django 2.1.15 on 2024-07-08 09:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0004_auto_20240708_0909'),
        ('usuarios', '0001_initial'),
        ('sitios', '0006_auto_20240705_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependenciasactual',
            name='dependencias',
        ),
        migrations.RemoveField(
            model_name='dependenciasactual',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='dependenciasactual',
            name='tipoDoc',
        ),
        migrations.RemoveField(
            model_name='dependenciasactual',
            name='usuarioRegistro',
        ),
        migrations.AddField(
            model_name='dependencias',
            name='consec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dependencias',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoDepAct', to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='dependencias',
            name='fechaLiberacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dependencias',
            name='fechaOcupacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dependencias',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.DeleteModel(
            name='DependenciasActual',
        ),
    ]
