# Generated by Django 2.1.15 on 2024-07-09 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0008_auto_20240708_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialdependencias',
            name='fechaLiberacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
