# Generated by Django 2.1.15 on 2024-07-09 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0009_auto_20240709_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencias',
            name='fechaLiberacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='dependencias',
            name='fechaOcupacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
