# Generated by Django 2.1.15 on 2024-07-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0010_auto_20240709_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='sedesclinica',
            name='nit',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
