# Generated by Django 2.1.15 on 2024-08-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20240710_1531'),
        ('sitios', '0011_sedesclinica_nit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dependencias',
            unique_together={('tipoDoc', 'documento')},
        ),
    ]
