# Generated by Django 2.1.15 on 2024-11-15 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0012_auto_20240812_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialdependencias',
            name='fechaOcupacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
