# Generated by Django 2.1.15 on 2024-08-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_auto_20240812_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triage',
            name='escalaDolor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='estatura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='frecCardiaca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='frecRespiratoria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='glasgow',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='glucometria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='peso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='saturacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='taDiast',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='taMedia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='taSist',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='temperatura',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
