# Generated by Django 2.1.15 on 2024-09-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0004_alter_triage_estadoreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='consecAdmision',
            field=models.IntegerField(default=0),
        ),
    ]
