# Generated by Django 2.1.15 on 2024-07-18 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_tipostarifa'),
        ('contratacion', '0002_procedimientos_usuarioregistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('vigenciaDesde', models.DateTimeField()),
                ('vigenciaHasta', models.DateTimeField()),
                ('porcTarifario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcSuministros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valorOxigeno', models.DecimalField(decimal_places=2, max_digits=8)),
                ('porcEsterilizacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcMaterial', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hospitalario', models.CharField(blank=True, max_length=1, null=True)),
                ('urgencias', models.CharField(blank=True, max_length=1, null=True)),
                ('ambulatorio', models.CharField(blank=True, max_length=1, null=True)),
                ('consultaExterna', models.CharField(blank=True, max_length=1, null=True)),
                ('copago', models.CharField(blank=True, max_length=1, null=True)),
                ('moderadora', models.CharField(blank=True, max_length=1, null=True)),
                ('tipofactura', models.CharField(blank=True, max_length=1, null=True)),
                ('agrupada', models.CharField(blank=True, max_length=1, null=True)),
                ('facturacionSuministros', models.CharField(blank=True, max_length=1, null=True)),
                ('facturacionCups', models.CharField(blank=True, max_length=1, null=True)),
                ('cuentaContable', models.CharField(blank=True, max_length=20, null=True)),
                ('requisitos', models.CharField(blank=True, max_length=2000, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Empresas')),
                ('tipoTarifa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.TiposTarifa')),
            ],
        ),
    ]
