# Generated by Django 2.1.15 on 2024-09-17 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0022_auto_20240917_0845'),
        ('planta', '0003_auto_20240702_1521'),
        ('contratacion', '0005_conveniosdetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenios',
            name='tipoTarifa',
        ),
        migrations.AddField(
            model_name='convenios',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='conveniosdetalle',
            name='tarifaSuministros',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.TarifasSuministros'),
        ),
    ]
