# Generated by Django 2.1.15 on 2024-09-30 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0006_auto_20240917_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conveniosdetalle',
            name='tarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifas.Tarifas'),
        ),
        migrations.AlterField(
            model_name='conveniosdetalle',
            name='tarifaSuministros',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifas.TarifasSuministros'),
        ),
    ]
