# Generated by Django 2.1.15 on 2024-10-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0007_auto_20240930_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='descripcion',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='conveniosdetalle',
            name='valorPropio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
