# Generated by Django 2.1.15 on 2024-10-16 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0012_liquidacionhonorarios_descripcion'),
        ('contratacion', '0008_auto_20241016_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifas.TiposTarifa'),
        ),
    ]
