# Generated by Django 2.1.15 on 2024-10-16 10:39

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0012_conveniosdetalle_codigocups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conveniosdetalle',
            name='tarifa',
            field=smart_selects.db_fields.GroupedForeignKey(blank=True, group_field='tipoTarifa', null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifas.Tarifas'),
        ),
    ]
