# Generated by Django 2.1.15 on 2024-10-18 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0003_auto_20240702_1521'),
        ('tarifas', '0016_liquidacionhonorarios_codigosuministro'),
        ('contratacion', '0013_auto_20241016_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConveniosLiquidacionHonorarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valorNeto', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contratacion.Convenios')),
                ('liquidacionHonorario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifas.LiquidacionHonorarios')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantas212', to='planta.Planta')),
            ],
        ),
        migrations.RenameField(
            model_name='conveniosdetalle',
            old_name='valorPropio',
            new_name='valorNeto',
        ),
    ]
