# Generated by Django 2.1.15 on 2024-10-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0015_auto_20241021_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conveniosliquidacionhonorarios',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='conveniosliquidacionhonorarios',
            name='liquidacionTarifa',
        ),
        migrations.RemoveField(
            model_name='conveniosliquidacionhonorarios',
            name='usuarioRegistro',
        ),
        migrations.DeleteModel(
            name='ConveniosLiquidacionHonorarios',
        ),
    ]
