# Generated by Django 2.1.15 on 2024-10-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0017_auto_20241021_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conveniosdetalle',
            name='codigoCups',
        ),
        migrations.RemoveField(
            model_name='conveniosdetalle',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='conveniosdetalle',
            name='tarifa',
        ),
        migrations.RemoveField(
            model_name='conveniosdetalle',
            name='tarifaSuministros',
        ),
        migrations.RemoveField(
            model_name='conveniosdetalle',
            name='tipoTarifa',
        ),
        migrations.RemoveField(
            model_name='conveniosdetalle',
            name='usuarioRegistro',
        ),
        migrations.DeleteModel(
            name='ConveniosDetalle',
        ),
    ]
