# Generated by Django 2.1.15 on 2024-10-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0019_auto_20241024_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimientos',
            name='tiposExamen',
        ),
        migrations.RemoveField(
            model_name='procedimientos',
            name='usuarioRegistro',
        ),
        migrations.DeleteModel(
            name='Procedimientos',
        ),
    ]
