# Generated by Django 2.1.15 on 2024-10-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0020_auto_20241024_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenios',
            name='tipoTarifa',
        ),
    ]
