# Generated by Django 2.1.15 on 2024-10-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0096_auto_20241023_1432'),
        ('tarifas', '0033_tarifas_valor'),
        ('facturacion', '0054_auto_20241023_1529'),
        ('contratacion', '0022_conveniosprocedimientos_concepto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conveniosprocedimientos',
            unique_together={('tipoTarifa', 'cups')},
        ),
        migrations.AlterUniqueTogether(
            name='conveniossuministros',
            unique_together={('tipoTarifa', 'suministro')},
        ),
        migrations.AlterUniqueTogether(
            name='conveniostarifashonorarios',
            unique_together={('tipoTarifa', 'tipoHonorario')},
        ),
    ]
