# Generated by Django 2.1.15 on 2024-10-30 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0054_auto_20241023_1529'),
        ('tarifas', '0037_tarifassuministros_concepto'),
        ('contratacion', '0024_conveniossuministros_concepto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conveniossuministros',
            unique_together={('convenio', 'tipoTarifa', 'suministro')},
        ),
    ]
