# Generated by Django 2.1.15 on 2024-10-30 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0037_tarifassuministros_concepto'),
        ('contratacion', '0025_auto_20241030_0916'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conveniostarifashonorarios',
            unique_together={('convenio', 'tipoTarifa', 'tipoHonorario')},
        ),
    ]
