# Generated by Django 2.1.15 on 2024-10-30 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0054_auto_20241023_1529'),
        ('clinico', '0096_auto_20241023_1432'),
        ('contratacion', '0027_conveniosliquidaciontarifashonorarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conveniosliquidaciontarifashonorarios',
            old_name='codigoSuministro',
            new_name='suministro',
        ),
        migrations.RemoveField(
            model_name='conveniosliquidaciontarifashonorarios',
            name='codigoCups',
        ),
        migrations.AddField(
            model_name='conveniosliquidaciontarifashonorarios',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Concepto224', to='facturacion.Conceptos'),
        ),
        migrations.AddField(
            model_name='conveniosliquidaciontarifashonorarios',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contratacion.Convenios'),
        ),
        migrations.AddField(
            model_name='conveniosliquidaciontarifashonorarios',
            name='cups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups209', to='clinico.Examenes'),
        ),
    ]
