# Generated by Django 2.1.15 on 2024-10-31 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0096_auto_20241023_1432'),
        ('tarifas', '0041_liquidaciontarifashonorarios_concepto'),
        ('contratacion', '0028_auto_20241030_1524'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conveniosprocedimientos',
            unique_together={('convenio', 'tipoTarifa', 'cups')},
        ),
    ]
