# Generated by Django 2.1.15 on 2024-09-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripscums',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
