# Generated by Django 2.1.15 on 2024-09-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0002_auto_20240927_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripsformafarmaceutica',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ripsformafarmaceutica',
            name='codigo',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
