# Generated by Django 2.1.15 on 2024-10-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0004_auto_20240927_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='RipsDci',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
    ]
