# Generated by Django 2.1.15 on 2024-10-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0005_ripsdci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripsconsultas',
            name='tipoDiagnosticoPrincipal',
            field=models.CharField(choices=[('Impresion Diagnostica', 'Impresion Diagnostica'), ('Confirmado nuevo', 'Confirmado nuevo'), ('Confirmado repetido', 'Confirmado REPETIDO')], default='A', editable=False, max_length=21),
        ),
        migrations.AlterField(
            model_name='ripsreciennacido',
            name='codSexoBiologico',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Indeterminado', 'Indeterminado')], default='A', editable=False, max_length=13),
        ),
        migrations.AlterField(
            model_name='ripsusuarios',
            name='codSexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Indeterminado', 'Indeterminado')], default='A', editable=False, max_length=13),
        ),
        migrations.AlterField(
            model_name='ripsusuarios',
            name='codZonaTerritorialResidencia',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urbano', 'Urbano')], default='A', editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='ripsusuarios',
            name='incapacidad',
            field=models.CharField(choices=[('Si', 'Si'), ('NO', 'No')], default='A', editable=False, max_length=2),
        ),
    ]
