# Generated by Django 2.1.15 on 2024-10-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0006_auto_20241008_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ripscums',
            name='codigo',
        ),
        migrations.AddField(
            model_name='ripscums',
            name='administracion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ripscums',
            name='codigoAtc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ripscums',
            name='cum',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ripscums',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ripscums',
            name='invima',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ripscums',
            name='nombreAtc',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ripscums',
            name='principioActivo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ripscums',
            name='nombre',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
