# Generated by Django 2.1.15 on 2024-10-23 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0095_auto_20241023_0837'),
        ('rips', '0007_auto_20241023_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripscums',
            name='viaAdministracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ViasAdmon10', to='clinico.ViasAdministracion'),
        ),
    ]
