# Generated by Django 2.1.15 on 2024-07-11 12:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conceptos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('codAd', models.CharField(default='A', editable=False, max_length=2)),
                ('codAt', models.CharField(default='A', editable=False, max_length=3)),
                ('ripsAc', models.CharField(default='A', editable=False, max_length=1)),
                ('ripsAp', models.CharField(default='A', editable=False, max_length=1)),
                ('ripsAt', models.CharField(default='A', editable=False, max_length=1)),
                ('ripsAm', models.CharField(default='A', editable=False, max_length=1)),
                ('ripsAh', models.CharField(default='A', editable=False, max_length=1)),
                ('ripsAu', models.CharField(default='A', editable=False, max_length=1)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('codigoCups', models.CharField(max_length=15)),
                ('autoriza', models.CharField(max_length=1)),
                ('codigoRips', models.CharField(max_length=15)),
                ('cupsGrupo', models.CharField(max_length=15)),
                ('cupsSubgrupo', models.CharField(max_length=15)),
                ('cupsCategoria', models.CharField(max_length=15)),
                ('resolucion1132', models.CharField(max_length=15)),
                ('nivelAtencion', models.CharField(max_length=15)),
                ('centroCosto', models.CharField(max_length=15)),
                ('finalidad', models.CharField(max_length=1)),
                ('duracion', models.CharField(max_length=15)),
                ('manejaInterfaz', models.CharField(max_length=1)),
                ('distribucionTerceros', models.CharField(max_length=1)),
                ('consentimientoInformado', models.CharField(max_length=1)),
                ('cita1Vez', models.CharField(max_length=1)),
                ('cuentaContable', models.CharField(max_length=20)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Conceptos')),
            ],
        ),
        migrations.CreateModel(
            name='TiposCups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='conceptos',
            name='tipoCups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.TiposCups'),
        ),
    ]
