# Generated by Django 2.1.15 on 2024-08-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0004_auto_20240826_1008'),
        ('usuarios', '0004_auto_20240822_0828'),
        ('facturacion', '0007_eapb'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conveniospacienteingresos',
            unique_together={('tipoDoc', 'documento', 'consecAdmision', 'convenio')},
        ),
    ]
