# Generated by Django 2.1.15 on 2024-09-11 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0060_auto_20240910_1654'),
        ('facturacion', '0008_auto_20240828_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimenesTipoPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('año', models.IntegerField(blank=True, null=True)),
                ('valorModeradora', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valorCopago', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valorTopeMaximoCopagoEvento', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valorTopeMaximoCopagoCalendario', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('regimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Regimenes')),
            ],
        ),
        migrations.CreateModel(
            name='SalariosLegales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='regimenestipopago',
            name='salarioLegal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.SalariosLegales'),
        ),
    ]
