# Generated by Django 2.1.15 on 2024-09-12 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0063_auto_20240912_0830'),
        ('facturacion', '0009_auto_20240911_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suministros',
            name='formaFarmaceutica',
        ),
        migrations.AddField(
            model_name='suministros',
            name='formasFarmaceutica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.FormasFarmaceuticas'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='principioActivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.PrincipiosActivos'),
        ),
    ]
