# Generated by Django 2.1.15 on 2024-09-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_auto_20240912_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='suministros',
            name='descripcionComercial',
            field=models.CharField(default='A', editable=False, max_length=250),
        ),
        migrations.AddField(
            model_name='suministros',
            name='fechaExpedicion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suministros',
            name='fechaVencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suministros',
            name='registroSanitario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
