# Generated by Django 2.1.15 on 2024-09-16 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0070_auto_20240916_1046'),
        ('facturacion', '0011_auto_20240912_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grupoQxUvr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paquete', models.CharField(default='N', editable=False, max_length=1)),
                ('honorarios', models.CharField(default='N', editable=False, max_length=1)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('codigoCups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Examenes')),
            ],
        ),
        migrations.RenameModel(
            old_name='TiposCups',
            new_name='TiposEmpresa',
        ),
        migrations.AlterField(
            model_name='conceptos',
            name='tipoCups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='cups',
            name='codigoCups',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='tarifas',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Conceptos'),
        ),
        migrations.AddField(
            model_name='tarifas',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.TiposTarifa'),
        ),
    ]
