# Generated by Django 2.1.15 on 2024-09-16 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referencia', '0002_auto_20240916_1100'),
        ('autorizaciones', '0003_auto_20240916_1100'),
        ('cirugia', '0005_auto_20240916_1100'),
        ('facturacion', '0013_empresas_tipoempresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cups',
            name='concepto',
        ),
        migrations.DeleteModel(
            name='Cups',
        ),
    ]
