# Generated by Django 2.1.15 on 2024-09-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0016_salariosminimoslegales'),
    ]

    operations = [
        migrations.AddField(
            model_name='salariosminimoslegales',
            name='año',
            field=models.CharField(default='A', editable=False, max_length=5),
        ),
        migrations.AddField(
            model_name='salariosminimoslegales',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='salariosminimoslegales',
            name='valorSubsidio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
