# Generated by Django 2.1.15 on 2024-09-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0017_auto_20240916_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salariosminimoslegales',
            name='año',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
