# Generated by Django 2.1.15 on 2024-09-16 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0019_liquidacionhonorarios_salariosminimoslegales'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionderechossala',
            name='salariosMinimosLegales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.SalariosMinimosLegales'),
        ),
        migrations.AlterField(
            model_name='liquidacionderechossala',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacionhonorarios',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
