# Generated by Django 2.1.15 on 2024-09-17 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0072_auto_20240917_0842'),
        ('planta', '0003_auto_20240702_1521'),
        ('facturacion', '0020_auto_20240916_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifasSuministros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoHomologado', models.CharField(blank=True, max_length=20, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Conceptos')),
                ('suministro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Suministros')),
                ('tipoTarifa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.TiposTarifa')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta')),
            ],
        ),
        migrations.CreateModel(
            name='Uvr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('año', models.IntegerField(default=0)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('tipoTarifa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.TiposTarifa')),
            ],
        ),
        migrations.RenameField(
            model_name='liquidacionderechossala',
            old_name='codigo',
            new_name='codigoHomologado',
        ),
        migrations.RenameField(
            model_name='liquidacionhonorarios',
            old_name='codigo',
            new_name='codigoHomologado',
        ),
        migrations.RenameField(
            model_name='tarifas',
            old_name='grupoQxUvr',
            new_name='cantidadUvr',
        ),
        migrations.AddField(
            model_name='conceptosafacturar',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='liquidacionderechossala',
            name='cantidadUvr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='liquidacionderechossala',
            name='codigoCups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Examenes'),
        ),
        migrations.AddField(
            model_name='liquidacionhonorarios',
            name='cantidadUvr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='liquidacionhonorarios',
            name='codigoCups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Examenes'),
        ),
        migrations.AddField(
            model_name='tarifas',
            name='codigoHomologado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tarifas',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AlterField(
            model_name='liquidacionhonorarios',
            name='salMinLeg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='tarifas',
            name='honorarios',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tarifas',
            name='paquete',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tarifas',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
