# Generated by Django 2.1.15 on 2024-09-17 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0021_auto_20240917_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacionderechossala',
            name='codigoCups',
        ),
        migrations.RemoveField(
            model_name='liquidacionhonorarios',
            name='codigoCups',
        ),
    ]
