# Generated by Django 2.1.15 on 2024-09-17 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0003_auto_20240702_1521'),
        ('clinico', '0073_auto_20240917_0902'),
        ('facturacion', '0022_auto_20240917_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionDerechos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoHomologado', models.CharField(blank=True, max_length=10, null=True)),
                ('salMinLeg', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('grupoQx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.GruposQx')),
                ('salariosMinimosLegales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.SalariosMinimosLegales')),
                ('tipoSala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.TiposSalas')),
                ('tipoTarifa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.TiposTarifa')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionDerechosIss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoHomologado', models.CharField(blank=True, max_length=10, null=True)),
                ('desdeUvr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('hastaUvr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('suministro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Suministros')),
                ('tipoSala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.TiposSalas')),
                ('tipoTarifa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.TiposTarifa')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionHonorariosIss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoHomologado', models.CharField(blank=True, max_length=10, null=True)),
                ('cantidadUvr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('codigoCups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Examenes')),
                ('tipoHonorario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.TiposHonorarios')),
                ('tipoTarifa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.TiposTarifa')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta')),
            ],
        ),
        migrations.RemoveField(
            model_name='liquidacionderechossala',
            name='grupoQx',
        ),
        migrations.RemoveField(
            model_name='liquidacionderechossala',
            name='salariosMinimosLegales',
        ),
        migrations.RemoveField(
            model_name='liquidacionderechossala',
            name='tipoSala',
        ),
        migrations.RemoveField(
            model_name='liquidacionderechossala',
            name='tipoTarifa',
        ),
        migrations.AddField(
            model_name='liquidacionhonorarios',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='uvr',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.DeleteModel(
            name='LiquidacionDerechosSala',
        ),
    ]
