# Generated by Django 2.1.15 on 2024-09-17 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0003_auto_20240702_1521'),
        ('facturacion', '0023_auto_20240917_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionCirugias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cirujanoPorcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('anestesiologoPorcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ayudantePorcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('derechosSalaPorcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('materialesPorcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('tipoTarifa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.TiposTarifa')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta')),
            ],
        ),
    ]
