# Generated by Django 2.1.15 on 2024-09-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0025_auto_20240917_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suministros',
            name='descripcionComercial',
            field=models.CharField(default='A', max_length=250),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='nombreGenerico',
            field=models.CharField(default='A', max_length=250),
        ),
    ]
