# Generated by Django 2.1.15 on 2024-09-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0026_auto_20240917_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suministros',
            name='descripcionComercial',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='nombreGenerico',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
