# Generated by Django 2.1.15 on 2024-09-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0028_auto_20240917_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacioncirugias',
            name='tipo',
            field=models.CharField(default='A', editable=False, max_length=50),
        ),
    ]
