# Generated by Django 2.1.15 on 2024-09-30 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0003_auto_20240930_0846'),
        ('facturacion', '0031_facturacion_facturaciondetalle_formasliquidacion_liquidacion_liquidaciondetalle_refacturacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacioncirugias',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifas.TiposTarifa'),
        ),
        migrations.AlterField(
            model_name='liquidacionderechos',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifas.TiposTarifa'),
        ),
        migrations.AlterField(
            model_name='liquidacionderechosiss',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifas.TiposTarifa'),
        ),
        migrations.AlterField(
            model_name='liquidacionhonorarios',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifas.TiposTarifa'),
        ),
        migrations.AlterField(
            model_name='liquidacionhonorariosiss',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifas.TiposTarifa'),
        ),
        migrations.AlterField(
            model_name='tarifas',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifas.TiposTarifa'),
        ),
        migrations.AlterField(
            model_name='tarifassuministros',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifas.TiposTarifa'),
        ),
        migrations.AlterField(
            model_name='uvr',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifas.TiposTarifa'),
        ),
        migrations.DeleteModel(
            name='TiposTarifa',
        ),
    ]
