# Generated by Django 2.1.15 on 2024-09-30 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0007_auto_20240930_0851'),
        ('facturacion', '0032_auto_20240930_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifas',
            name='codigoCups',
        ),
        migrations.RemoveField(
            model_name='tarifas',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='tarifas',
            name='tipoTarifa',
        ),
        migrations.RemoveField(
            model_name='tarifas',
            name='usuarioRegistro',
        ),
        migrations.DeleteModel(
            name='Tarifas',
        ),
    ]
