# Generated by Django 2.1.15 on 2024-09-30 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0035_auto_20240930_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacionhonorarios',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifas.TiposHonorarios'),
        ),
        migrations.AlterField(
            model_name='liquidacionhonorariosiss',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifas.TiposHonorarios'),
        ),
        migrations.DeleteModel(
            name='TiposHonorarios',
        ),
    ]
