# Generated by Django 2.1.15 on 2024-09-30 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0036_auto_20240930_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacionhonorarios',
            name='grupoQx',
        ),
        migrations.RemoveField(
            model_name='liquidacionhonorarios',
            name='salariosMinimosLegales',
        ),
        migrations.RemoveField(
            model_name='liquidacionhonorarios',
            name='tipoHonorario',
        ),
        migrations.RemoveField(
            model_name='liquidacionhonorarios',
            name='tipoTarifa',
        ),
        migrations.RemoveField(
            model_name='liquidacionhonorarios',
            name='usuarioRegistro',
        ),
        migrations.DeleteModel(
            name='LiquidacionHonorarios',
        ),
    ]
