# Generated by Django 2.1.15 on 2024-09-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0037_auto_20240930_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacionhonorariosiss',
            name='codigoCups',
        ),
        migrations.RemoveField(
            model_name='liquidacionhonorariosiss',
            name='tipoHonorario',
        ),
        migrations.RemoveField(
            model_name='liquidacionhonorariosiss',
            name='tipoTarifa',
        ),
        migrations.RemoveField(
            model_name='liquidacionhonorariosiss',
            name='usuarioRegistro',
        ),
        migrations.DeleteModel(
            name='LiquidacionHonorariosIss',
        ),
    ]
