# Generated by Django 2.1.15 on 2024-09-30 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0038_auto_20240930_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uvr',
            name='tipoTarifa',
        ),
        migrations.RemoveField(
            model_name='uvr',
            name='usuarioRegistro',
        ),
        migrations.DeleteModel(
            name='Uvr',
        ),
    ]
