# Generated by Django 2.1.15 on 2024-09-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0041_auto_20240930_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacionderechosiss',
            name='suministro',
        ),
        migrations.RemoveField(
            model_name='liquidacionderechosiss',
            name='tipoSala',
        ),
        migrations.RemoveField(
            model_name='liquidacionderechosiss',
            name='tipoTarifa',
        ),
        migrations.DeleteModel(
            name='LiquidacionDerechosIss',
        ),
    ]
