# Generated by Django 2.1.15 on 2024-10-01 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0005_ripsdci'),
        ('facturacion', '0043_auto_20240930_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='suministros',
            name='ripsCums',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsCums01', to='rips.RipsCums'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='ripsDci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsDci01', to='rips.RipsDci'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='ripsFormaFarmaceutica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsFfm01', to='rips.RipsFormaFarmaceutica'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='ripsTipoMedicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsTipoMedicamento'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='ripsUnidadDispensa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsDispensa01', to='rips.RipsUnidadUpr'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='ripsUnidadMedica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsUnidad01', to='rips.RipsUmm'),
        ),
    ]
