# Generated by Django 2.1.15 on 2024-10-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0045_auto_20241001_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suministros',
            name='ripsCums',
        ),
        migrations.RemoveField(
            model_name='suministros',
            name='ripsDci',
        ),
        migrations.RemoveField(
            model_name='suministros',
            name='ripsFormaFarmaceutica',
        ),
        migrations.RemoveField(
            model_name='suministros',
            name='ripsTipoMedicamento',
        ),
        migrations.RemoveField(
            model_name='suministros',
            name='ripsUnidadDispensa',
        ),
        migrations.RemoveField(
            model_name='suministros',
            name='ripsUnidadMedica',
        ),
    ]
