# Generated by Django 2.1.15 on 2024-10-16 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0012_liquidacionhonorarios_descripcion'),
        ('facturacion', '0047_auto_20241001_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='suministros',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifas.TiposHonorarios'),
        ),
    ]
