# Generated by Django 2.1.15 on 2024-10-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0048_suministros_tipohonorario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suministros',
            name='cums',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
