# Generated by Django 2.1.15 on 2024-10-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0051_auto_20241018_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptos',
            name='tipoCups',
        ),
    ]
