# Generated by Django 2.1.15 on 2024-10-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0053_suministros_cantidaduvr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suministros',
            name='nombre',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='nombreGenerico',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
