# Generated by Django 2.1.15 on 2024-11-08 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0041_liquidaciontarifashonorarios_concepto'),
        ('facturacion', '0055_auto_20241101_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaciondetalle',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario099', to='tarifas.TiposHonorarios'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='tipoRegistro',
            field=models.CharField(blank=True, choices=[('M', 'MANUAL'), ('S', 'SISTEMA')], max_length=20, null=True),
        ),
    ]
