# Generated by Django 2.1.15 on 2024-11-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0056_auto_20241108_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacion',
            name='totalRecibido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='totalRecibido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
