# Generated by Django 2.1.15 on 2024-11-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0057_auto_20241121_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refacturacion',
            old_name='facturaFinal',
            new_name='facturaAnulada',
        ),
        migrations.RenameField(
            model_name='refacturacion',
            old_name='facturaInicial',
            new_name='facturaNueva',
        ),
    ]
