# Generated by Django 2.1.15 on 2024-06-28 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('admisiones', '0001_initial'),
        ('sitios', '0001_initial'),
        ('planta', '0001_initial'),
        ('clinico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='dependenciasActual',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id1', to='sitios.DependenciasActual'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dependenciasIngreso',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id0', to='sitios.Dependencias'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dependenciasSalida',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id2', to='sitios.Dependencias'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='documento',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento', to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dxActual',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id4', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dxIngreso',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id3', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dxSalida',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id5', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='especialidadesMedicosActual',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EspAct', to='clinico.Especialidades'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='especialidadesMedicosIngreso',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EspIng', to='clinico.Especialidades'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='especialidadesMedicosSalida',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EspSal', to='clinico.Especialidades'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='estadoSalida',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.EstadosSalida'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='medicoActual',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id7', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='medicoIngreso',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id6', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='medicoSalida',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id8', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='sedesClinica',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='tipoDoc',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
    ]
