# Generated by Django 2.1.15 on 2024-07-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0002_auto_20240628_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresos',
            name='fechaIngreso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='fechaRegistro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='fechaSalida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
