# Generated by Django 2.1.15 on 2024-07-08 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0006_auto_20240708_0909'),
        ('usuarios', '0001_initial'),
        ('admisiones', '0003_auto_20240704_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='ActaDefuncion',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ViasEgreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.ViasEgreso'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ViasIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.ViasIngreso'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='causasExterna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.CausasExterna'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='fechaMuerte',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='hClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='medicoDefuncion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Medicos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='muerte',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='regimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Regimenes'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='salidaMotivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EspSal', to='clinico.TiposSalidas'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='tiposCotizante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposCotizante'),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='dependenciasActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id1', to='sitios.Dependencias'),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='dependenciasIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id0', to='sitios.Dependencias'),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='dependenciasSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id2', to='sitios.Dependencias'),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento', to='usuarios.Usuarios'),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='dxActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id4', to='clinico.Diagnosticos'),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='dxIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id3', to='clinico.Diagnosticos'),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='dxSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id5', to='clinico.Diagnosticos'),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='especialidadesMedicosActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EspAct', to='clinico.Especialidades'),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='especialidadesMedicosIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EspIng', to='clinico.Especialidades'),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='especialidadesMedicosSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EspSal', to='clinico.Especialidades'),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='estadoSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.EstadosSalida'),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='medicoActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id7', to='planta.Planta'),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='medicoIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id6', to='planta.Planta'),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='medicoSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id8', to='planta.Planta'),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica', to='sitios.SedesClinica'),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
    ]
