# Generated by Django 2.1.15 on 2024-07-09 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0008_hallazgos'),
        ('sitios', '0008_auto_20240708_0910'),
        ('planta', '0003_auto_20240702_1521'),
        ('usuarios', '0002_auto_20240708_0909'),
        ('admisiones', '0004_auto_20240708_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaSolicita', models.DateTimeField(blank=True, null=True)),
                ('fechaAtendio', models.DateTimeField(blank=True, null=True)),
                ('consec', models.IntegerField()),
                ('hClinica', models.CharField(default='', max_length=50)),
                ('motivo', models.CharField(default='', max_length=1000)),
                ('examenFisico', models.CharField(default='', max_length=5000)),
                ('frecCardiaca', models.IntegerField()),
                ('frecRespiratoria', models.IntegerField()),
                ('taSist', models.IntegerField()),
                ('taDiast', models.IntegerField()),
                ('taMedia', models.IntegerField()),
                ('glasgow', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('temperatura', models.IntegerField()),
                ('estatura', models.IntegerField()),
                ('glucometria', models.IntegerField()),
                ('saturacion', models.IntegerField()),
                ('escalaDolor', models.IntegerField()),
                ('vistobno', models.CharField(default='', max_length=1)),
                ('tipoTrauma', models.CharField(default='', max_length=20)),
                ('cinematicaTrauma', models.CharField(default='', max_length=5)),
                ('tipoIngreso', models.CharField(default='', max_length=20)),
                ('fechaModanexo', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.CharField(default='', max_length=200)),
                ('alergiasTriage', models.CharField(default='', max_length=50)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='A', editable=False, max_length=1)),
                ('causaExterna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.CausasExterna')),
                ('clasificacionTriage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposTriage')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento1', to='usuarios.Usuarios')),
                ('enfermedaActual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Enfermedades')),
                ('regimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Regimenes')),
                ('sedesClinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica1', to='sitios.SedesClinica')),
                ('tipoDoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento')),
                ('tiposCotizante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposCotizante')),
                ('usuarioAtiende', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento2', to='planta.Planta')),
                ('usuarioAutoriza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta')),
                ('usuarioCrea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento3', to='planta.Planta')),
                ('viaEgreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.ViasEgreso')),
            ],
        ),
    ]
