# Generated by Django 2.1.15 on 2024-07-09 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0011_nivelesregimenes_nombre'),
        ('admisiones', '0006_furips'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='serviciosActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id10', to='clinico.Servicios'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='serviciosIng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id9', to='clinico.Servicios'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='serviciosSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id11', to='clinico.Servicios'),
        ),
    ]
