# Generated by Django 2.1.15 on 2024-07-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0007_auto_20240709_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresos',
            name='hClinica',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
