# Generated by Django 2.1.15 on 2024-07-11 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20240710_1531'),
        ('admisiones', '0010_auto_20240710_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='contactoAcompañante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Contac01', to='usuarios.UsuariosContacto'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='contactoResponsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Contac02', to='usuarios.UsuariosContacto'),
        ),
    ]
