# Generated by Django 2.1.15 on 2024-07-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20240710_1531'),
        ('admisiones', '0012_auto_20240711_1204'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingresos',
            unique_together={('tipoDoc', 'documento', 'consec')},
        ),
    ]
