# Generated by Django 2.1.15 on 2024-08-01 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0013_auto_20240716_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triage',
            name='causaExterna',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='clasificacionTriage',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='enfermedaActual',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='regimen',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='sedesClinica',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='tipoDoc',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='tiposCotizante',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='usuarioAtiende',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='usuarioAutoriza',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='usuarioCrea',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='viaEgreso',
        ),
        migrations.DeleteModel(
            name='Triage',
        ),
    ]
