# Generated by Django 3.2 on 2024-09-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0014_auto_20240801_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furips',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'ACTIVO'), ('I', 'INACTIVO')], default='A', editable=False, max_length=1),
        ),
    ]
