# Generated by Django 2.1.15 on 2024-09-25 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20240919_1605'),
        ('admisiones', '0016_auto_20240924_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='furips',
            name='consec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='furips',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documentofur', to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='furips',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AlterField(
            model_name='furips',
            name='condicionAccidentado',
            field=models.CharField(choices=[('A', 'Asegurado'), ('N', 'No Asegurado'), ('V', 'Vehiculo Fantasma'), ('P', 'Poliza Falsa'), ('F', 'Vehiculo en fuga')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='furips',
            name='estado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=20, null=True),
        ),
    ]
