# Generated by Django 2.1.15 on 2024-09-27 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0004_auto_20240927_1135'),
        ('admisiones', '0019_auto_20240927_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='ripsServiciosActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripssServicios02', to='rips.RipsServicios'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsServiciosIng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripssServicios01', to='rips.RipsServicios'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsServiciosSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripssServicios03', to='rips.RipsServicios'),
        ),
    ]
