# Generated by Django 2.1.15 on 2024-09-30 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0020_auto_20240927_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresos',
            name='ripsDestinoUsuarioEgresoRecienNacido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripssServicios03', to='rips.RipsDestinoEgreso'),
        ),
    ]
