# Generated by Django 2.1.15 on 2024-09-30 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0022_auto_20240930_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresos',
            name='ripsCondicionDestinoUsuarioEgreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripssServicios10', to='rips.RipsDestinoEgreso'),
        ),
    ]
