# Generated by Django 2.1.15 on 2024-09-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0023_auto_20240930_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresos',
            name='ripsDestinoUsuarioEgresoRecienNacido',
        ),
    ]
