# Generated by Django 2.1.15 on 2024-10-01 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0025_ingresos_ripsdestinousuarioegresoreciennacido'),
    ]

    operations = [
     #   migrations.AlterField(
     #       model_name='ingresos',
     #       name='ripsDestinoUsuarioEgresoRecienNacido',
     #       field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripssDestino10', to='rips.RipsDestinoEgreso'),
     #   ),
    ]
