# Generated by Django 2.1.15 on 2024-10-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0029_remove_ingresos_ripsdestinousuarioegresoreciennacido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furips',
            name='amparoReclamaAFosygaGastos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='furips',
            name='amparoReclamaAFosygaQx',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='furips',
            name='amparoReclamaFacturadoGastos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='furips',
            name='amparoReclamaFacturadoQx',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
    ]
