# Generated by Django 2.1.15 on 2024-10-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0030_auto_20241011_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furips',
            name='condicionAccidentado',
            field=models.CharField(blank=True, choices=[('A', 'Asegurado'), ('N', 'No Asegurado'), ('V', 'Vehiculo Fantasma'), ('P', 'Poliza Falsa'), ('F', 'Vehiculo en fuga')], default='A', editable=False, max_length=1, null=True),
        ),
    ]
