# Generated by Django 2.1.15 on 2024-10-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0031_auto_20241015_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furips',
            name='consecVictima',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
