# Generated by Django 2.1.15 on 2024-10-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0032_auto_20241015_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furips',
            name='zonaEvento',
            field=models.CharField(blank=True, default='A', editable=False, max_length=1, null=True),
        ),
    ]
