# Generated by Django 2.1.15 on 2024-06-28 20:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sitios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abreviatura', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=50)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TiposUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='L', max_length=1)),
                ('fechaNacio', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('contacto', models.CharField(max_length=50)),
                ('imagen', models.ImageField(null=True, upload_to='fotos')),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('centrosC', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Centros')),
                ('ciudades', smart_selects.db_fields.ChainedForeignKey(chained_field='departamentos', chained_model_field='departamentos', on_delete=django.db.models.deletion.CASCADE, to='sitios.Ciudades')),
                ('departamentos', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Departamentos')),
                ('tipoDoc', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento')),
                ('tiposUsuario', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposUsuario')),
            ],
        ),
    ]
