# Generated by Django 2.1.15 on 2024-07-08 09:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0007_auto_20240708_0909'),
        ('basicas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosContacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='L', max_length=1)),
                ('fechaNacio', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('consecPaciente', models.IntegerField()),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('ciudades', smart_selects.db_fields.ChainedForeignKey(chained_field='departamentos', chained_model_field='departamentos', on_delete=django.db.models.deletion.CASCADE, to='sitios.Ciudades')),
                ('departamentos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Departamentos')),
            ],
        ),
        migrations.AddField(
            model_name='tiposdocumento',
            name='tiposDocCodigoDian',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='estadoCivil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicas.EstadoCivil'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Localidades'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Municipios'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='ocupacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicas.Ocupaciones'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Paises'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='centrosC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Centros'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='departamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Departamentos'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='tiposUsuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposUsuario'),
        ),
        migrations.AddField(
            model_name='usuarioscontacto',
            name='documentoPaciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='usuarioscontacto',
            name='tipoDoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tipoDoc01', to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='usuarioscontacto',
            name='tipoDocPaciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='usuarioscontacto',
            name='tiposContacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicas.TiposContacto'),
        ),
        migrations.AddField(
            model_name='usuarioscontacto',
            name='tiposFamilia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicas.TiposFamilia'),
        ),
    ]
