# Generated by Django 2.1.15 on 2024-07-10 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20240708_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='contacto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fechaNacio',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
