# Generated by Django 2.1.15 on 2024-08-22 08:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20240710_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioscontacto',
            name='fechaNacio',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
