# Generated by Django 2.1.15 on 2024-09-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20240822_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioscontacto',
            name='consecPaciente',
        ),
        migrations.RemoveField(
            model_name='usuarioscontacto',
            name='documentoPaciente',
        ),
        migrations.RemoveField(
            model_name='usuarioscontacto',
            name='tipoDocPaciente',
        ),
    ]
