# Generated by Django 2.1.15 on 2024-07-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planta', '0003_auto_20240702_1521'),
        ('usuarios', '0003_auto_20240710_1531'),
        ('facturacion', '0006_conveniospaciente_conveniospacienteingresos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacionMedicamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consecAdmision', models.IntegerField(default=0)),
                ('folio', models.IntegerField(default=0)),
                ('orden', models.IntegerField(default=0)),
                ('fecha_ini', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('cantidadAdministrada', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dosisAdministrada', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoria65', to='usuarios.Usuarios')),
                ('suministro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Suministros')),
                ('tipoDoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta')),
            ],
        ),
    ]
