# Generated by Django 2.1.15 on 2024-07-19 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20240710_1531'),
        ('planta', '0003_auto_20240702_1521'),
        ('enfermeria', '0004_dolorenfermeria'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeridasEnfermeria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consecAdmision', models.IntegerField(default=0)),
                ('folio', models.IntegerField(default=0)),
                ('area', models.CharField(max_length=3000)),
                ('tipoHerida', models.CharField(max_length=100)),
                ('diasPop', models.CharField(max_length=100)),
                ('tamaño', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('materialOrganico', models.BooleanField()),
                ('enrojecimiento', models.BooleanField()),
                ('necrosis', models.BooleanField()),
                ('secrecion', models.BooleanField()),
                ('edema', models.BooleanField()),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoria2113', to='usuarios.Usuarios')),
                ('tipoDoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermeria.TurnosEnfermeria')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta')),
            ],
        ),
    ]
