# Generated by Django 2.1.15 on 2024-07-19 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0003_auto_20240702_1521'),
        ('usuarios', '0003_auto_20240710_1531'),
        ('enfermeria', '0007_posicionpacientesenfermeria'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotasLiquidosEnfermeria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consecAdmision', models.IntegerField(default=0)),
                ('folio', models.IntegerField(default=0)),
                ('liquido', models.DecimalField(decimal_places=0, max_digits=5)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=5)),
                ('tipo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=200)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoria568', to='usuarios.Usuarios')),
                ('tipoDoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermeria.TurnosEnfermeria')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta')),
            ],
        ),
    ]
