# Generated by Django 2.1.15 on 2024-07-19 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0003_auto_20240702_1521'),
        ('usuarios', '0003_auto_20240710_1531'),
        ('enfermeria', '0009_notasenfermeria'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceLiquidosEnfermeria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consecAdmision', models.IntegerField(default=0)),
                ('folio', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField()),
                ('liquido', models.DecimalField(decimal_places=0, max_digits=5)),
                ('horaUno', models.CharField(max_length=100)),
                ('horaDos', models.CharField(max_length=100)),
                ('horaTres', models.CharField(max_length=100)),
                ('horaCuatro', models.CharField(max_length=100)),
                ('horaCinco', models.CharField(max_length=100)),
                ('horaSeis', models.CharField(max_length=100)),
                ('horaSiete', models.CharField(max_length=100)),
                ('horaOcho', models.CharField(max_length=100)),
                ('horaNueve', models.CharField(max_length=100)),
                ('horaDiez', models.CharField(max_length=100)),
                ('horaOnce', models.CharField(max_length=100)),
                ('horaDoce', models.CharField(max_length=100)),
                ('horaTrece', models.CharField(max_length=100)),
                ('horaCatorce', models.CharField(max_length=100)),
                ('horaQuince', models.CharField(max_length=100)),
                ('horaDiezYSeis', models.CharField(max_length=100)),
                ('horaDiezYSiete', models.CharField(max_length=100)),
                ('horaDiezYOcho', models.CharField(max_length=100)),
                ('horaDiezYNueve', models.CharField(max_length=100)),
                ('horaVeinte', models.CharField(max_length=100)),
                ('horaVeinteYUno', models.CharField(max_length=100)),
                ('horaVeinteyDos', models.CharField(max_length=100)),
                ('horaVeinteyTres', models.CharField(max_length=100)),
                ('horaVeinteyCuatro', models.CharField(max_length=100)),
                ('medicamento', models.IntegerField(default=0)),
                ('totalAdministrado', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('residuoMezclas', models.IntegerField(default=0)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('adminMañana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin001', to='planta.Planta')),
                ('adminNoche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin003', to='planta.Planta')),
                ('adminTarfe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin002', to='planta.Planta')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoria212', to='usuarios.Usuarios')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermeria.TipoBalanceLiquidosEnfermeria')),
                ('tipoDoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermeria.TurnosEnfermeria')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta')),
            ],
        ),
    ]
