# Generated by Django 2.1.15 on 2024-07-11 12:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_auto_20240710_1531'),
        ('planta', '0003_auto_20240702_1521'),
        ('clinico', '0012_ips'),
        ('sitios', '0011_sedesclinica_nit'),
        ('facturacion', '0002_auto_20240711_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hClinica', models.CharField(blank=True, max_length=20, null=True)),
                ('consec', models.IntegerField()),
                ('fechaSolicitud', models.DateTimeField(blank=True, null=True)),
                ('prioritario', models.CharField(blank=True, max_length=1, null=True)),
                ('justificacion', models.CharField(blank=True, max_length=5000, null=True)),
                ('numeroAutorizacion', models.CharField(blank=True, max_length=5000, null=True)),
                ('fechaAutorizacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=1000, null=True)),
                ('estadoAutorizacion', models.CharField(blank=True, max_length=1, null=True)),
                ('fechaModifica', models.DateTimeField(blank=True, null=True)),
                ('numeroSoclicitud', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fechaVigencia', models.DateTimeField(blank=True, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento7', to='usuarios.Usuarios')),
                ('dxPrinc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dx21', to='clinico.Diagnosticos')),
                ('dxRel1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dx22', to='clinico.Diagnosticos')),
                ('dxRel2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dx23', to='clinico.Diagnosticos')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento77', to='facturacion.Empresas')),
                ('medicoAutoriza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Medicos')),
                ('plantaAutoriza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta1', to='planta.Planta')),
                ('plantaSolicita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.Usuarios')),
                ('sedesClinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica13', to='sitios.SedesClinica')),
                ('tipoDoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta2', to='planta.Planta')),
            ],
        ),
        migrations.CreateModel(
            name='AutorizacionesCirugias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hClinica', models.CharField(blank=True, max_length=20, null=True)),
                ('consec', models.IntegerField()),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('autorizacionesId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento99', to='autorizaciones.Autorizaciones')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento9', to='usuarios.Usuarios')),
                ('sedesClinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica5', to='sitios.SedesClinica')),
                ('tipoDoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioRegistroPlanta2', to='planta.Planta')),
            ],
        ),
        migrations.CreateModel(
            name='AutorizacionesCups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hClinica', models.CharField(blank=True, max_length=20, null=True)),
                ('consec', models.IntegerField()),
                ('autorizado', models.CharField(blank=True, max_length=1, null=True)),
                ('cantidadSolicitada', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cantidadAutorizada', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('autorizacionesId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento88', to='autorizaciones.Autorizaciones')),
                ('codigocups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento888', to='facturacion.Cups')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento8', to='usuarios.Usuarios')),
                ('sedesClinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica14', to='sitios.SedesClinica')),
                ('tipoDoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento')),
                ('usuarioRegistro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Planta3', to='planta.Planta')),
            ],
        ),
    ]
