# Generated by Django 2.1.15 on 2024-07-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autorizacionescups',
            old_name='codigocups',
            new_name='codigoCups',
        ),
    ]
