# Generated by Django 2.1.15 on 2024-09-16 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0002_auto_20240711_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacionescups',
            name='codigoCups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento888', to='clinico.TiposExamen'),
        ),
    ]
