# Generated by Django 2.1.15 on 2024-07-19 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0003_auto_20240702_1521'),
        ('facturacion', '0006_conveniospaciente_conveniospacienteingresos'),
        ('sitios', '0011_sedesclinica_nit'),
        ('usuarios', '0003_auto_20240710_1531'),
        ('cirugia', '0003_recordanestesico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacionCirugias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('estadoSala', models.CharField(default='L', max_length=50)),
                ('fecha_programacion', models.DateTimeField()),
                ('hora_programacion', models.CharField(blank=True, max_length=5, null=True)),
                ('consecAdmision', models.IntegerField(default=0)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('cups1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups80', to='facturacion.Cups')),
                ('cups2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups81', to='facturacion.Cups')),
                ('cups3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups82', to='facturacion.Cups')),
                ('cups4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups83', to='facturacion.Cups')),
                ('cups5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups84', to='facturacion.Cups')),
                ('cups6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups85', to='facturacion.Cups')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoria123', to='usuarios.Usuarios')),
                ('sedesClinica_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.SedesClinica')),
                ('serviciosSedes_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.ServiciosSedes')),
                ('subServiciosSedes_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.SubServiciosSedes')),
                ('tipoDoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta')),
            ],
        ),
    ]
