# Generated by Django 2.1.15 on 2024-09-16 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0004_programacioncirugias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirugias',
            name='cups1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups60', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='cups10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups69', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='cups11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups70', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='cups12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups71', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='cups13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups72', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='cups14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups73', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='cups15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups74', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='cups2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups61', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='cups3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups62', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='cups4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups63', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='cups5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups64', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='cups6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups65', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='cups7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups66', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='cups8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups67', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='cups9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups68', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='programacioncirugias',
            name='cups1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups80', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='programacioncirugias',
            name='cups2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups81', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='programacioncirugias',
            name='cups3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups82', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='programacioncirugias',
            name='cups4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups83', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='programacioncirugias',
            name='cups5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups84', to='clinico.TiposExamen'),
        ),
        migrations.AlterField(
            model_name='programacioncirugias',
            name='cups6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups85', to='clinico.TiposExamen'),
        ),
    ]
