# Generated by Django 2.1.15 on 2024-09-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0006_finalidadcirugia_intervencioncirugias_organoscirugias_planificacioncirugia_tiposheridasoperatorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='GravedadCirugia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ZonasCirugia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
    ]
