# Generated by Django 2.1.15 on 2024-09-30 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinico', '0085_auto_20240927_1157'),
        ('facturacion', '0031_facturacion_facturaciondetalle_formasliquidacion_liquidacion_liquidaciondetalle_refacturacion'),
        ('planta', '0003_auto_20240702_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormasLiquidacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantas205', to='planta.Planta')),
            ],
        ),
        migrations.CreateModel(
            name='GruposQx',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionCirugias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='A', editable=False, max_length=50)),
                ('cirujanoPorcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('anestesiologoPorcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ayudantePorcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('derechosSalaPorcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('materialesPorcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionDerechos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoHomologado', models.CharField(blank=True, max_length=10, null=True)),
                ('salMinLeg', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('grupoQx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GrupoQx12', to='facturacion.GruposQx')),
                ('salariosMinimosLegales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SalMinLeg12', to='facturacion.SalariosMinimosLegales')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionDerechosIss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoHomologado', models.CharField(blank=True, max_length=10, null=True)),
                ('desdeUvr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('hastaUvr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('suministro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoSuminiistro112', to='facturacion.Suministros')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionHonorarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoHomologado', models.CharField(blank=True, max_length=10, null=True)),
                ('salMinLeg', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cantidadUvr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('grupoQx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GrupoQx01', to='facturacion.GruposQx')),
                ('salariosMinimosLegales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MinLeg01', to='facturacion.SalariosMinimosLegales')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionHonorariosIss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoHomologado', models.CharField(blank=True, max_length=10, null=True)),
                ('cantidadUvr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('codigoCups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups105', to='clinico.Examenes')),
            ],
        ),
        migrations.CreateModel(
            name='Tarifas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('codigoHomologado', models.CharField(blank=True, max_length=10, null=True)),
                ('cantidadUvr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('paquete', models.CharField(blank=True, max_length=1, null=True)),
                ('honorarios', models.CharField(blank=True, max_length=1, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('codigoCups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups101', to='clinico.Examenes')),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Concepto01', to='facturacion.Conceptos')),
            ],
        ),
        migrations.CreateModel(
            name='TarifasSuministros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoHomologado', models.CharField(blank=True, max_length=20, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Concepto02', to='facturacion.Conceptos')),
                ('suministro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Suministro101', to='facturacion.Suministros')),
            ],
        ),
        migrations.CreateModel(
            name='TiposHonorarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TiposSalas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TiposTarifa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Uvr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('año', models.IntegerField(default=0)),
                ('valor', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('tipoTarifa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa05', to='facturacion.TiposTarifa')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantas204', to='planta.Planta')),
            ],
        ),
        migrations.AddField(
            model_name='tarifassuministros',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa02', to='facturacion.TiposTarifa'),
        ),
        migrations.AddField(
            model_name='tarifassuministros',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='platas201', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='tarifas',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa01', to='facturacion.TiposTarifa'),
        ),
        migrations.AddField(
            model_name='tarifas',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantas200', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='liquidacionhonorariosiss',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario101', to='facturacion.TiposHonorarios'),
        ),
        migrations.AddField(
            model_name='liquidacionhonorariosiss',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa04', to='facturacion.TiposTarifa'),
        ),
        migrations.AddField(
            model_name='liquidacionhonorariosiss',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantas203', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='liquidacionhonorarios',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario01', to='facturacion.TiposHonorarios'),
        ),
        migrations.AddField(
            model_name='liquidacionhonorarios',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa03', to='facturacion.TiposTarifa'),
        ),
        migrations.AddField(
            model_name='liquidacionhonorarios',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantas212', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='liquidacionderechosiss',
            name='tipoSala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoSala01', to='facturacion.TiposSalas'),
        ),
        migrations.AddField(
            model_name='liquidacionderechosiss',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa07', to='facturacion.TiposTarifa'),
        ),
        migrations.AddField(
            model_name='liquidacionderechos',
            name='tipoSala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoSala03', to='facturacion.TiposSalas'),
        ),
        migrations.AddField(
            model_name='liquidacionderechos',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa08', to='facturacion.TiposTarifa'),
        ),
        migrations.AddField(
            model_name='liquidacioncirugias',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa06', to='facturacion.TiposTarifa'),
        ),
        migrations.AddField(
            model_name='liquidacioncirugias',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantas206', to='planta.Planta'),
        ),
    ]
