# Generated by Django 2.1.15 on 2024-09-30 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0002_conceptosafacturar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacioncirugias',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa06', to='tarifas.TiposTarifa'),
        ),
        migrations.AlterField(
            model_name='liquidacionderechos',
            name='grupoQx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GrupoQx12', to='tarifas.GruposQx'),
        ),
        migrations.AlterField(
            model_name='liquidacionderechos',
            name='tipoSala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoSala03', to='tarifas.TiposSalas'),
        ),
        migrations.AlterField(
            model_name='liquidacionderechos',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa08', to='tarifas.TiposTarifa'),
        ),
        migrations.AlterField(
            model_name='liquidacionderechosiss',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa07', to='tarifas.TiposTarifa'),
        ),
        migrations.AlterField(
            model_name='liquidacionhonorarios',
            name='grupoQx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GrupoQx01', to='tarifas.GruposQx'),
        ),
        migrations.AlterField(
            model_name='liquidacionhonorarios',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario01', to='tarifas.TiposHonorarios'),
        ),
        migrations.AlterField(
            model_name='liquidacionhonorarios',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa03', to='tarifas.TiposTarifa'),
        ),
        migrations.AlterField(
            model_name='liquidacionhonorariosiss',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario101', to='tarifas.TiposHonorarios'),
        ),
        migrations.AlterField(
            model_name='liquidacionhonorariosiss',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa04', to='tarifas.TiposTarifa'),
        ),
        migrations.AlterField(
            model_name='tarifas',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa01', to='tarifas.TiposTarifa'),
        ),
        migrations.AlterField(
            model_name='tarifassuministros',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa02', to='tarifas.TiposTarifa'),
        ),
        migrations.AlterField(
            model_name='uvr',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa05', to='tarifas.TiposTarifa'),
        ),
    ]
