# Generated by Django 2.1.15 on 2024-10-15 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0005_tarifas_uvraño'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarifas',
            old_name='valor',
            new_name='valorIss',
        ),
        migrations.RemoveField(
            model_name='tarifas',
            name='honorarios',
        ),
        migrations.AddField(
            model_name='tarifas',
            name='grupoQx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Grupo01', to='tarifas.GruposQx'),
        ),
        migrations.AddField(
            model_name='tarifas',
            name='valorSoat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
