# Generated by Django 2.1.15 on 2024-10-15 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0047_auto_20241001_1507'),
        ('tarifas', '0006_auto_20241015_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruposqx',
            name='salMinLeg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='gruposqx',
            name='salariosMinimosLegales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MinLeg02', to='facturacion.SalariosMinimosLegales'),
        ),
    ]
