# Generated by Django 2.1.15 on 2024-10-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0007_auto_20241015_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifas',
            name='valorIss',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tarifas',
            name='valorSoat',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
