# Generated by Django 2.1.15 on 2024-10-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0008_auto_20241015_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifas',
            name='cantidadUvr',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
