# Generated by Django 2.1.15 on 2024-10-16 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0009_auto_20241015_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionhonorarios',
            name='uvrAño',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Uvr103', to='tarifas.Uvr'),
        ),
    ]
