# Generated by Django 2.1.15 on 2024-10-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0010_liquidacionhonorarios_uvraño'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionhonorarios',
            name='valorIss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
