# Generated by Django 2.1.15 on 2024-10-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0013_auto_20241016_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifas',
            name='valorPropio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
