# Generated by Django 2.1.15 on 2024-10-17 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0048_suministros_tipohonorario'),
        ('tarifas', '0014_tarifas_valorpropio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifas',
            name='codigoSuministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Suminis123', to='facturacion.Suministros'),
        ),
    ]
