# Generated by Django 2.1.15 on 2024-10-17 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0049_auto_20241017_1208'),
        ('tarifas', '0015_tarifas_codigosuministro'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionhonorarios',
            name='codigoSuministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Suminis127', to='facturacion.Suministros'),
        ),
    ]
