# Generated by Django 2.1.15 on 2024-10-18 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0003_auto_20240702_1521'),
        ('clinico', '0092_examenes_uvraño'),
        ('tarifas', '0016_liquidacionhonorarios_codigosuministro'),
    ]

    operations = [
        migrations.CreateModel(
            name='OxigenoIss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=30, null=True)),
                ('metroHoraFraccion', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('codigoCups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups112', to='clinico.Examenes')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantas210', to='planta.Planta')),
            ],
        ),
        migrations.RenameField(
            model_name='liquidacionhonorarios',
            old_name='miaxUvr',
            new_name='valorSoat',
        ),
        migrations.RenameField(
            model_name='liquidacionhonorariosiss',
            old_name='cantidadUvr',
            new_name='miaxUvr',
        ),
        migrations.RemoveField(
            model_name='gruposqx',
            name='salMinLeg',
        ),
        migrations.RemoveField(
            model_name='gruposqx',
            name='salariosMinimosLegales',
        ),
        migrations.RemoveField(
            model_name='liquidacionhonorarios',
            name='minUvr',
        ),
        migrations.RemoveField(
            model_name='liquidacionhonorariosiss',
            name='codigoCups',
        ),
        migrations.RemoveField(
            model_name='liquidacionhonorariosiss',
            name='codigoHomologado',
        ),
        migrations.RemoveField(
            model_name='liquidacionhonorariosiss',
            name='tipoTarifa',
        ),
        migrations.AddField(
            model_name='liquidacionhonorariosiss',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='liquidacionhonorariosiss',
            name='minUvr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='liquidacionhonorariosiss',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacionhonorarios',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantas217', to='planta.Planta'),
        ),
        migrations.AlterField(
            model_name='liquidacionhonorariosiss',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario102', to='tarifas.TiposHonorarios'),
        ),
    ]
