# Generated by Django 2.1.15 on 2024-10-18 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0003_auto_20240702_1521'),
        ('tarifas', '0018_auto_20241018_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='HonorariosIss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('minUvr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('maxUvr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('tipoHonorario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario122', to='tarifas.TiposHonorarios')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantas223', to='planta.Planta')),
            ],
        ),
    ]
