# Generated by Django 2.1.15 on 2024-10-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0019_honorariosiss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacionhonorariosiss',
            name='tipoHonorario',
        ),
        migrations.RemoveField(
            model_name='liquidacionhonorariosiss',
            name='usuarioRegistro',
        ),
        migrations.DeleteModel(
            name='LiquidacionHonorariosIss',
        ),
    ]
