# Generated by Django 2.1.15 on 2024-10-21 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0052_remove_conceptos_tipocups'),
        ('planta', '0003_auto_20240702_1521'),
        ('tarifas', '0021_auto_20241018_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='HonorariosSoat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('salMinLeg', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('grupoQx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GrupoQx11', to='tarifas.GruposQx')),
                ('salariosMinimosLegales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MinLeg111', to='facturacion.SalariosMinimosLegales')),
                ('tipoHonorario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario222', to='tarifas.TiposHonorarios')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantas333', to='planta.Planta')),
            ],
        ),
    ]
