# Generated by Django 2.1.15 on 2024-10-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0022_honorariossoat'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorariosiss',
            name='codigoHomologado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='honorariossoat',
            name='codigoHomologado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
