# Generated by Django 2.1.15 on 2024-10-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0025_liquidaciontarifas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacionderechos',
            name='grupoQx',
        ),
        migrations.RemoveField(
            model_name='liquidacionderechos',
            name='salariosMinimosLegales',
        ),
        migrations.RemoveField(
            model_name='liquidacionderechos',
            name='tipoSala',
        ),
        migrations.RemoveField(
            model_name='liquidacionderechos',
            name='tipoTarifa',
        ),
        migrations.DeleteModel(
            name='LiquidacionDerechos',
        ),
    ]
