# Generated by Django 2.1.15 on 2024-10-21 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0027_auto_20241021_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorariossoat',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa111', to='tarifas.TiposTarifa'),
        ),
    ]
