# Generated by Django 2.1.15 on 2024-10-21 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0028_honorariossoat_tipotarifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorariosiss',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa1122', to='tarifas.TiposTarifa'),
        ),
    ]
