# Generated by Django 2.1.15 on 2024-10-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0029_honorariosiss_tipotarifa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifas',
            name='nombre',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
