# Generated by Django 2.1.15 on 2024-10-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0031_remove_tarifassuministros_concepto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formasliquidacion',
            name='usuarioRegistro',
        ),
        migrations.RemoveField(
            model_name='liquidacionderechosiss',
            name='suministro',
        ),
        migrations.RemoveField(
            model_name='liquidacionderechosiss',
            name='tipoSala',
        ),
        migrations.RemoveField(
            model_name='liquidacionderechosiss',
            name='tipoTarifa',
        ),
        migrations.DeleteModel(
            name='FormasLiquidacion',
        ),
        migrations.DeleteModel(
            name='LiquidacionDerechosIss',
        ),
    ]
