# Generated by Django 2.1.15 on 2024-10-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0034_auto_20241029_0715'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='honorariosiss',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='honorariossoat',
            unique_together=set(),
        ),
    ]
