# Generated by Django 2.1.15 on 2024-10-29 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0035_auto_20241029_0804'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liquidaciontarifashonorarios',
            unique_together=set(),
        ),
    ]
