# Generated by Django 2.1.15 on 2024-10-30 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0037_tarifassuministros_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorariosiss',
            name='tipoSalas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoSalas122', to='tarifas.TiposSalas'),
        ),
        migrations.AddField(
            model_name='honorariossoat',
            name='tipoSalas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoSalas123', to='tarifas.TiposSalas'),
        ),
    ]
