# Generated by Django 2.1.15 on 2024-10-30 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0054_auto_20241023_1529'),
        ('tarifas', '0040_auto_20241030_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidaciontarifashonorarios',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Concepto229', to='facturacion.Conceptos'),
        ),
    ]
