# Generated by Django 2.1.15 on 2024-07-09 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basicas', '0003_furipslista_furipsparametro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodos',
            name='diaFinal',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='periodos',
            name='diaInicial',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
