# Generated by Django 2.1.15 on 2024-09-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicas', '0005_archivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='tipo',
            field=models.CharField(choices=[('P', 'Plano'), ('R', 'Reporte')], default='P', editable=False, max_length=1),
        ),
    ]
